import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {normalizeCandidates,decisionRequest,resolveDecisions,decidePrompt} from '../plugins/studio-library/jev.js';
import {installBuiltinPreset} from './install-builtin-preset.mjs';
const input={description:'一个白发女孩撑着红伞',candidates:[{tag:'1girl',category:'count',explicit:true,evidence:'一个'},{tag:'white_hair',category:'appearance',explicit:true,evidence:'白发'},{tag:'red_umbrella',category:'clothing',explicit:true,evidence:'红伞'},{tag:'soft_lighting',category:'lighting',explicit:false}]};
const answer={answers:{t0:{type:'score',score:2},t1:{type:'score',score:2},t2:{type:'score',score:0.4},t3:{type:'score',score:1.6}}};
test('market and Jev are wired into product, not only helper files',async()=>{const build=await fs.readFile('harness/build-community.mjs','utf8'),tools=await fs.readFile('harness/plugins/studio-tools/index.js','utf8'),ui=await fs.readFile('harness/plugins/studio-library/client.js','utf8');assert.match(build,/dshmarket/);assert.match(tools,/langbai_decide_prompt/);assert.match(ui,/智能提示词/);});
test('Jev covers positive content only and preserves explicit semantics without amplifying inferred tags',()=>{const c=normalizeCandidates(input);assert.equal(c[1].tag,'white hair');const out=resolveDecisions(c,answer);assert.ok(out.positivePrompt.includes('red umbrella'));assert.equal(out.warnings.length,1);assert.equal(out.selected[0].weight,1);assert.equal(out.selected.find(x=>!x.explicit).weight,1);assert.equal(out.styleChanged,false);assert.equal(out.negativeChanged,false);assert.equal(decisionRequest(input.description,c).model,'typesafe/jev-1.13');});
test('reject forged explicit evidence, style candidates and malformed Jev responses',()=>{assert.throws(()=>normalizeCandidates({...input,candidates:[{...input.candidates[0],evidence:'男人'}]}));assert.throws(()=>normalizeCandidates({...input,candidates:[{tag:'artist:test',category:'style',explicit:false}]}));assert.throws(()=>resolveDecisions(normalizeCandidates(input),{answers:{}}));});
test('mutually exclusive explicit candidates produce an error instead of losing user intent',()=>{const c=normalizeCandidates({description:'站着坐着',candidates:[{tag:'standing',category:'pose',explicit:true,evidence:'站着',group:'pose'},{tag:'sitting',category:'pose',explicit:true,evidence:'坐着',group:'pose'}]});assert.throws(()=>resolveDecisions(c,{answers:{t0:{type:'score',score:2},t1:{type:'score',score:2}}}));});
test('no configured Jev or unverified mature tag means no API request',async()=>{let calls=0;const deps={config:{enabled:true,apiKey:'TEST'},lookup:async()=>[],fetchImpl:async()=>{calls++}};await assert.rejects(decidePrompt(input,deps));await assert.rejects(decidePrompt(input,{...deps,config:{enabled:false}}));assert.equal(calls,0);});
test('valid request sends one decision batch and never sends style/configuration to Jev',async()=>{let calls=0;const out=await decidePrompt(input,{config:{enabled:true,apiKey:'TEST'},lookup:async tag=>[{tag}],fetchImpl:async(url,args)=>{calls++;assert.equal(url,'https://api.defapi.org/api/v1/decisions');assert.equal(args.redirect,'error');const body=JSON.parse(args.body);assert.equal(body.state.description,input.description);assert.equal(body.questions.t2.type,'score');assert.equal('apiKey' in body,false);return {ok:true,json:async()=>answer};}});assert.equal(calls,1);assert.ok(out.positivePrompt);});
test('built-in preset installation is idempotent and preserves existing custom default and edited content',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'studio-preset-'));let creates=0;const rows=[{id:'custom',name:'我的预设'}];let last;const store={list:async()=>({items:rows,total:rows.length}),get:async()=>({name:'我的预设'}),create:async(data,opts)=>{creates++;last=opts;rows.push({id:'new',...data});return {id:'new'};}};await installBuiltinPreset(store,dir,{name:'无限四代 · Studio'},()=>false);await installBuiltinPreset(store,dir,{name:'无限四代 · Studio'},()=>false);assert.equal(creates,1);assert.equal(last.makeDefault,false);});

