import {test} from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs/promises';import path from 'node:path';
import {createMaterialWorkflow} from '../plugins/studio-data/session-materials.js';
import {convertMaterial} from '../plugins/studio-data/material-converter.js';
import {normalizeLoreBook} from '../../.tmp/harness-community/packages/dsh-roleplay-rp-lore-book/src/activation.js';
async function fixture(){
 const root=path.resolve('artifacts/agent-session-materials-20260927/fixtures');await fs.mkdir(root,{recursive:true});const directory=await fs.mkdtemp(root+'/case-');
 let source={name:'Rain',description:'world',exampleMessages:'example',entries:Array.from({length:70},(_,i)=>({id:String(i),keys:['rain'],content:'Rain '+i,position:'before-character',insertionOrder:42,enabled:true}))};
 let profile={revision:1,runtime:{executionMode:'agent'},resources:{lorebooks:[{id:'old'}],card:{id:'previous'}},cast:[],scene:{}};
 let approvals=0,creates=0,binds=0,allow=true,refreshFail=false;const assets=new Map();let onConfirm=()=>{},onCreate=()=>{},failBind=false;
 const asset={async create(value){creates++;await onCreate();const id='copy-'+creates;assets.set(id,{id,revision:1,...value});await fs.writeFile(path.join(directory,id+'.json'),JSON.stringify(assets.get(id)));return {detail:assets.get(id)};},async detail(id){if(!assets.has(id))throw Error('missing');return assets.get(id);}};
 const sessions={get:()=>profile,async bindAssetChangesDuringRun(_agent,{expectedRevision,changes}){if(failBind)throw Error('fixture binding failure');assert.equal(expectedRevision,profile.revision);binds++;profile={...profile,revision:profile.revision+1,resources:{...profile.resources,...(changes.cardId?{card:{id:changes.cardId}}:{}),...(changes.personaId?{persona:{id:changes.personaId}}:{}),...(changes.presetId?{preset:{id:changes.presetId}}:{}),...(changes.lorebookIds?{lorebooks:changes.lorebookIds.map(id=>({id}))}:{})}};return profile;}};
 const deps={directory,normalizeLoreBook,source:async()=>({item:source}),confirm:async()=>{approvals++;await onConfirm();return allow;},resolve:()=>({asset,sessions,runtime:{refreshRunContext:async()=>{if(refreshFail)throw Error('fixture refresh failure');}}})};
 const make=()=>createMaterialWorkflow(deps);let flow=make();
 const call=(args,id='one')=>flow.execute(args,{callId:id,agent:{session:{id:'session-1'}}});
 const inspect=collection=>call({action:'inspect',collection,id:'local'},'inspect');
 const apply=(collection,expectedRevision,id='one')=>call({action:'apply',collection,id:'local',expectedRevision},id);
 return {call,inspect,apply,assets,get stats(){return {approvals,creates,binds}},get profile(){return profile},set profile(p){profile=p},set source(s){source=s},set allow(v){allow=v},set refreshFail(v){refreshFail=v},set failBind(v){failBind=v},set onConfirm(v){onConfirm=v},set onCreate(v){onCreate=v},restart(){flow=make()},directory};
}
test('inspect/create/bind uses full 70-entry book; appends existing bindings; durable call replay after restart',async()=>{const f=await fixture();const p=await f.inspect('lorebooks');const r=await f.apply('lorebooks',p.expectedRevision);assert.equal(r.ok,true);assert.equal(f.assets.get(r.asset.id).entries.length,70);assert.deepEqual(f.profile.resources.lorebooks.map(x=>x.id),['old',r.asset.id]);f.restart();assert.deepEqual(await f.apply('lorebooks',p.expectedRevision),r);assert.deepEqual(f.stats,{approvals:1,creates:1,binds:1});});
test('no-op reuse avoids duplicate copies; original current card remains recoverable',async()=>{const f=await fixture();const p=await f.inspect('characters');const r=await f.apply('characters',p.expectedRevision);assert.equal(r.recovery.previousBindings.card.id,'previous');assert.equal(f.assets.get(r.asset.id).messageExample,'example');f.restart();const p2=await f.inspect('characters');assert.equal((await f.apply('characters',p2.expectedRevision,'two')).alreadyApplied,true);assert.equal(f.stats.creates,1);});
test('cancel performs no create or binding; changed local data and session revisions reject before writes',async()=>{const f=await fixture();let p=await f.inspect('characters');f.allow=false;assert.equal((await f.apply('characters',p.expectedRevision)).cancelled,true);assert.equal(f.stats.creates,0);f.allow=true;f.onConfirm=()=>{f.source={name:'Changed'}};await assert.rejects(f.apply('characters',p.expectedRevision,'two'),/变化/);assert.equal(f.stats.creates,0);p=await f.inspect('characters');f.profile={...f.profile,revision:42};await assert.rejects(f.apply('characters',p.expectedRevision,'three'),/变化/);});
test('Chat mode cannot write; hidden arguments and caller session spoofing rejected',async()=>{const f=await fixture();f.profile={...f.profile,runtime:{executionMode:'chat'}};const p=await f.inspect('characters');assert.equal(p.canApply,false);await assert.rejects(f.apply('characters',p.expectedRevision),/Agent 模式/);await assert.rejects(f.call({action:'inspect',collection:'characters',id:'local',sessionId:'other'}),/参数/);assert.equal(f.stats.creates,0);});
test('binding failure preserves saved copy and retries reuse; refresh failure reports persisted bind instead of lying',async()=>{const f=await fixture();let p=await f.inspect('characters');f.failBind=true;let r=await f.apply('characters',p.expectedRevision);assert.equal(r.binding.applied,false);assert.equal(f.stats.creates,1);f.failBind=false;f.refreshFail=true;p=await f.inspect('characters');r=await f.apply('characters',p.expectedRevision,'two');assert.equal(r.ok,false);assert.equal(r.binding.applied,true);assert.equal(r.contextRefreshed,false);assert.equal(f.stats.creates,1);});
test('source/session change during create leaves saved copy unbound; edited copy is never overwritten',async()=>{const f=await fixture();let p=await f.inspect('characters');f.onCreate=()=>{f.profile={...f.profile,revision:2}};let r=await f.apply('characters',p.expectedRevision);assert.equal(r.binding.applied,false);f.assets.get(r.asset.id).revision=2;p=await f.inspect('characters');await assert.rejects(f.apply('characters',p.expectedRevision,'two'),/副本已被修改/);assert.equal(f.stats.creates,1);});
test('uncertain create on restart never automatically duplicates',async()=>{const f=await fixture();const p=await f.inspect('characters');f.onCreate=()=>{throw Error('interrupted')};await assert.rejects(f.apply('characters',p.expectedRevision),/interrupted/);f.restart();await assert.rejects(f.apply('characters',p.expectedRevision,'two'),/未确定/);assert.equal(f.stats.creates,1);});
test('converter uses official lore semantics; preset does not falsely apply temperature; instructions are not silently injected',()=>{const book=convertMaterial('lorebooks',{name:'world',entries:[{id:'1',comment:'rain',content:'world',keys:['rain'],secondaryKeys:['wet'],selective:false,insertionOrder:42,position:'before-character'}]},normalizeLoreBook);assert.equal(book.value.entries[0].level,'worldDescription');assert.equal(book.value.entries[0].order,42);assert.deepEqual(book.value.entries[0].secondaryKeys,[]);const preset=convertMaterial('samplerPresets',{name:'p',systemPrompt:'top',jailbreakPrompt:'bottom',temperature:0.4});assert.equal(preset.value.fields.length,2);assert.match(preset.warnings.join(),/温度/);assert.ok(!('temperature' in preset.value));assert.match(convertMaterial('characters',{name:'card',systemPrompt:'hidden'}).warnings.join(),/不注入/);});
