// Generated from shared/tavern-image-ui.json.
const _imageUi = {
  "zh-CN": {
    "library": "画风 Tag 库",
    "hint": "仅修改右侧风格提示词；抽取预览不生图。",
    "search": "搜索 Tag / 中文含义",
    "all": "画风／媒介／光色",
    "local": "Danbooru 画风",
    "works": "动漫／游戏作品",
    "worksHint": "作品 Tag 也可能影响角色和题材。",
    "count": "随机数量",
    "min": "最低权重",
    "max": "最高权重",
    "seed": "抽卡种子",
    "pin": "固定保留",
    "selected": "已选",
    "draw": "抽取预览",
    "add": "添加所选",
    "apply": "添加预览结果",
    "undo": "撤销上次添加",
    "more": "载入更多",
    "empty": "没有匹配项；完整库可在设置中安装。",
    "error": "读取失败，请重试",
    "loading": "读取中…",
    "current": "当前画面与提示词",
    "changes": "本次局部修改",
    "preserved": "未修改的内容已保留",
    "review": "修改结果未通过连续性检查，旧提示词已保留。请确认后再生图。",
    "keep": "保留当前方案",
    "adopt": "采用模型新方案",
    "previous": "上一版",
    "close": "关闭",
    "clear": "清空选择",
    "reset": "开始新画面",
    "resetHint": "保留聊天与图片历史，下一次生图不继承当前画面。",
    "reroll": "换一组"
  },
  "zh-TW": {
    "library": "畫風 Tag 庫",
    "hint": "僅修改右側風格提示詞；抽取預覽不生圖。",
    "search": "搜尋 Tag / 中文含義",
    "all": "畫風／媒材／光色",
    "local": "Danbooru 畫風",
    "works": "動漫／遊戲作品",
    "worksHint": "作品 Tag 也可能影響角色和題材。",
    "count": "隨機數量",
    "min": "最低權重",
    "max": "最高權重",
    "seed": "抽卡種子",
    "pin": "固定保留",
    "selected": "已選",
    "draw": "抽取預覽",
    "add": "加入所選",
    "apply": "加入預覽結果",
    "undo": "復原上次加入",
    "more": "載入更多",
    "empty": "沒有符合項目；完整庫可在設定中安裝。",
    "error": "讀取失敗，請重試",
    "loading": "讀取中…",
    "current": "目前畫面與提示詞",
    "changes": "本次局部修改",
    "preserved": "未修改的內容已保留",
    "review": "修改結果未通過連續性檢查，舊提示詞已保留。請確認後再生圖。",
    "keep": "保留目前方案",
    "adopt": "採用模型新方案",
    "previous": "上一版",
    "close": "關閉",
    "clear": "清空選擇",
    "reset": "開始新畫面",
    "resetHint": "保留聊天與圖片歷史，下次生圖不繼承目前畫面。",
    "reroll": "換一組"
  },
  "en-US": {
    "library": "Style Tag library",
    "hint":
        "Only edits the style prompt; drawing a preview does not generate images.",
    "search": "Search tags or meanings",
    "all": "Style / medium / lighting",
    "local": "Danbooru styles",
    "works": "Anime / game sources",
    "worksHint": "Source tags may also affect characters and subject matter.",
    "count": "Random count",
    "min": "Min weight",
    "max": "Max weight",
    "seed": "Draw seed",
    "pin": "Pin / always include",
    "selected": "Selected",
    "draw": "Draw preview",
    "add": "Add selected",
    "apply": "Add preview result",
    "undo": "Undo last addition",
    "more": "Load more",
    "empty": "No matches; install the full tag database in Settings.",
    "error": "Load failed; retry",
    "loading": "Loading…",
    "current": "Current image prompt",
    "changes": "Changes this turn",
    "preserved": "Unchanged content preserved",
    "review":
        "Revision needs review. The previous prompt is preserved; confirm before generating.",
    "keep": "Keep current prompt",
    "adopt": "Use proposed rewrite",
    "previous": "Previous version",
    "close": "Close",
    "clear": "Clear selection",
    "reset": "Start a new image",
    "resetHint":
        "Keep chat and image history; the next image starts a fresh prompt.",
    "reroll": "Reroll"
  },
  "ja-JP": {
    "library": "画風タグライブラリ",
    "hint": "画風プロンプトのみ変更。抽選プレビューでは画像を生成しません。",
    "search": "タグ・意味を検索",
    "all": "画風・画材・光と色",
    "local": "Danbooru 画風",
    "works": "アニメ・ゲーム作品",
    "worksHint": "作品タグはキャラクターや題材にも影響します。",
    "count": "抽選数",
    "min": "最小ウェイト",
    "max": "最大ウェイト",
    "seed": "抽選シード",
    "pin": "固定して保持",
    "selected": "選択済み",
    "draw": "抽選プレビュー",
    "add": "選択タグを追加",
    "apply": "プレビューを追加",
    "undo": "最後の追加を取り消す",
    "more": "さらに読み込む",
    "empty": "該当なし。完全なタグDBは設定で導入できます。",
    "error": "読み込み失敗。再試行",
    "loading": "読み込み中…",
    "current": "現在の画像プロンプト",
    "changes": "今回の部分変更",
    "preserved": "未変更の内容を保持",
    "review": "変更の確認が必要です。以前のプロンプトを保持しました。生成前に確認してください。",
    "keep": "現在の案を保持",
    "adopt": "新しい案を採用",
    "previous": "前のバージョン",
    "close": "閉じる",
    "clear": "選択をクリア",
    "reset": "新しい画像を開始",
    "resetHint": "会話と画像履歴を保持し、次回は新しいプロンプトで開始します。",
    "reroll": "再抽選"
  },
  "ko-KR": {
    "library": "화풍 태그 라이브러리",
    "hint": "스타일 프롬프트만 변경합니다. 추첨 미리보기는 이미지를 생성하지 않습니다.",
    "search": "태그 / 의미 검색",
    "all": "화풍 / 매체 / 빛과 색",
    "local": "Danbooru 화풍",
    "works": "애니 / 게임 작품",
    "worksHint": "작품 태그는 캐릭터와 소재에도 영향을 줄 수 있습니다.",
    "count": "추첨 개수",
    "min": "최소 가중치",
    "max": "최대 가중치",
    "seed": "추첨 시드",
    "pin": "고정 / 항상 포함",
    "selected": "선택됨",
    "draw": "추첨 미리보기",
    "add": "선택 항목 추가",
    "apply": "미리보기 결과 추가",
    "undo": "마지막 추가 취소",
    "more": "더 불러오기",
    "empty": "검색 결과 없음. 설정에서 전체 태그 DB를 설치하세요.",
    "error": "불러오기 실패. 재시도",
    "loading": "불러오는 중…",
    "current": "현재 이미지 프롬프트",
    "changes": "이번 부분 변경",
    "preserved": "변경하지 않은 내용 유지",
    "review": "수정 확인이 필요합니다. 이전 프롬프트를 보존했습니다. 생성 전 확인하세요.",
    "keep": "현재 프롬프트 유지",
    "adopt": "새 제안 사용",
    "previous": "이전 버전",
    "close": "닫기",
    "clear": "선택 지우기",
    "reset": "새 이미지 시작",
    "resetHint": "대화와 이미지 기록은 유지하고 다음 이미지는 새 프롬프트로 시작합니다.",
    "reroll": "다시 추첨"
  }
};
Map<String, String> imageUi(String language) =>
    Map<String, String>.from(_imageUi[language] ?? _imageUi["en-US"]!);
