import React from 'react';import {createRoot} from 'react-dom/client';
import PiAgentPage from '../src/PiAgentPage';import {useAppStore} from '../src/store';import '../src/styles.css';
const settings:any={language:'zh-CN',agentApiProtocol:'openai-compatible',agentApiBaseUrl:'http://127.0.0.1:19357/v1',agentApiKey:'owned-fixture-key',agentApiModel:'owned-current',agentContextWindow:128000,agentMaxOutputTokens:8192,agentVisionEnabled:true,agentUiPreferences:{sidebarOpen:true},promptTemplates:[]};
const chat:any={id:'owned-chat',title:'Owned streaming chat',messages:[{id:'owned-assistant',role:'assistant',content:'Actual stream in progress',attachments:[],tools:[],status:'streaming',createdAt:new Date().toISOString()}],draftAttachments:[],status:'running',context:{used:0,limit:128000,percent:0},characterIds:[],lorebookIds:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
const workspace:any={version:4,conversations:[chat],selectedConversationId:chat.id,skills:[],memories:[],characters:[],personas:[],lorebooks:[],samplerPresets:[]};
const receipts:any[]=[];let onEvent:(e:any)=>void=()=>{};
async function add(files:any[]){for(const f of files){const a={id:String(receipts.length),name:f.name,kind:'text',mime:'text/plain',filePath:'owned-fixture-path',createdAt:new Date().toISOString(),size:f.bytes?.length??1};chat.draftAttachments.push(a);receipts.push({name:f.name,bytes:Array.from(f.bytes??[])});}return {ok:true,attachments:chat.draftAttachments};}
window.naiDesktop={getAgentWorkspace:async()=>structuredClone(workspace),getAgentPendingPermissions:async()=>[],getAgentPendingQuestions:async()=>[],onAgentEvent:(callback:any)=>{onEvent=callback;return()=>{}},setSetting:async(k:any,v:any)=>{settings[k]=v;return v},getSettings:async()=>structuredClone(settings),importAgentFiles:async()=>add([{name:'picker.txt',bytes:new TextEncoder().encode('picked')}]),importAgentFileData:async(_id:any,files:any)=>add(files),readClipboardImageFiles:async()=>[],readAgentClipboardFiles:async()=>[],discoverAgentModels:async()=>({ok:true,message:'owned list',models:Array.from({length:240},(_,i)=>({id:'owned-model-'+i,displayName:'Very long model '+i+' '+('long-id/'.repeat(15)),contextWindow:64000,metadataSource:'api'}))}),deleteAgentAttachment:async(_id:any,id:any)=>{chat.draftAttachments=chat.draftAttachments.filter((a:any)=>a.id!==id);return {ok:true,workspace:structuredClone(workspace)}}} as any;
(window as any).qa={receipts,workspace,settings,finish:()=>{chat.status='idle';onEvent({kind:'workspace',workspace:structuredClone(workspace)});}};
useAppStore.setState({settings});createRoot(document.getElementById('root')!).render(<PiAgentPage active/>);
