import 'dart:convert';import 'dart:io';
import 'package:flutter/material.dart';import 'package:flutter_test/flutter_test.dart';import 'package:flutter_secure_storage/flutter_secure_storage.dart';import 'package:shared_preferences/shared_preferences.dart';import 'package:path_provider_platform_interface/path_provider_platform_interface.dart';import 'package:provider/provider.dart';import 'package:image/image.dart' as image;
import 'package:novelai_mobile/services/storage.dart';import 'package:novelai_mobile/services/unified_storage.dart';import 'package:novelai_mobile/state/app_state.dart';import 'package:novelai_mobile/models/nai_models.dart';import 'package:novelai_mobile/screens/generate_screen.dart';
class _Paths extends PathProviderPlatform{final String root;_Paths(this.root);@override Future<String?> getApplicationDocumentsPath()async=>root;@override Future<String?> getTemporaryPath()async=>root;}
void main(){TestWidgetsFlutterBinding.ensureInitialized();late Directory root;late Storage storage;late AppState state;late HttpServer server;final requests=<String>[];var status=200;
 final bytes=image.encodePng(image.Image(width:2,height:2));
 Map<String,dynamic> config({String model='nai-diffusion-5-full'})=>{'baseUrl':'http://127.0.0.1:${server.port}/prefix/v1','model':model,'size':'1024x1024','responseFormat':'b64_json','extensions':<String,dynamic>{}};
 setUp(()async{HttpOverrides.global=null;requests.clear();status=200;root=Directory.systemTemp.createTempSync('issue32-envelope-owned-');PathProviderPlatform.instance=_Paths(root.path);UnifiedStorage.active=null;SharedPreferences.setMockInitialValues({});FlutterSecureStorage.setMockInitialValues({});storage=Storage();state=AppState(storage:storage,preloadCompletedImage:(_)async{})..settings=AppSettings(proxyMode:'direct',saveToGallery:false)..params.positivePrompt='owned test';await storage.setSettings(state.settings);await storage.setToken('QA_NATIVE_DO_NOT_FORWARD');server=await HttpServer.bind(InternetAddress.loopbackIPv4,0);server.listen((req)async{requests.add('${req.method} ${req.uri.path}');expect(req.headers.value('authorization'),'Bearer QA_RELAY_ONLY');req.response.headers.contentType=ContentType.json;req.response.statusCode=status;if(req.method=='GET'){expect(req.uri.path,'/prefix/v1/models');req.response.write(jsonEncode({'data':[{'id':'nai-diffusion-5-full'},{'id':'gpt-image-1'}]}));}else{expect(jsonDecode(await utf8.decoder.bind(req).join()),{'model':'nai-diffusion-5-full','prompt':'owned test','size':'1024x1024','n':1,'response_format':'b64_json'});req.response.write(jsonEncode({'data':[{'b64_json':base64Encode(bytes)}]}));}await req.response.close();});});
 tearDown(()async{state.dispose();await server.close(force:true);if(root.parent.path!=Directory.systemTemp.path||!root.path.split(Platform.pathSeparator).last.startsWith('issue32-envelope-owned-'))throw StateError('Unsafe cleanup');await root.delete(recursive:true);});
 test('readonly validation precedes secure persistent save without generation',()async{await state.saveCompatibleSettings(config(),'QA_RELAY_ONLY');expect(requests,['GET /prefix/v1/models']);final reopened=await Storage().getSettings();expect(reopened.imageProvider,'openai-images');expect(await storage.getCompatibleImageKey(reopened.compatibleImage['credentialId']),'QA_RELAY_ONLY');expect(jsonEncode(reopened.toJson()),isNot(contains('QA_RELAY_ONLY')));expect(await storage.getToken(),'QA_NATIVE_DO_NOT_FORWARD');});
 test('failed validation does not save or switch the service',()async{status=401;final before=(await storage.getSettings()).toJson();await expectLater(state.saveCompatibleSettings(config(),'QA_RELAY_ONLY'),throwsA(anything));expect((await storage.getSettings()).toJson(),before);expect(state.settings.imageProvider,'novelai');expect(requests,['GET /prefix/v1/models']);});
 test('non-NovelAI model is rejected without network or save',()async{await expectLater(state.saveCompatibleSettings(config(model:'gpt-image-1'),'QA_RELAY_ONLY'),throwsA(anything));expect(requests,isEmpty);expect(state.settings.imageProvider,'novelai');});
 test('one generation POST yields real durable PNG/history without native credential forwarding',()async{await state.saveCompatibleSettings(config(),'QA_RELAY_ONLY');await state.generate();expect(requests,['GET /prefix/v1/models','POST /prefix/v1/images/generations']);expect(state.current,isNotNull);expect(File(state.current!.filePath).existsSync(),isTrue);expect(image.decodePng(await File(state.current!.filePath).readAsBytes())!.width,2);expect(state.busy,isFalse);expect(state.lastAnlasSpent,isNull);expect(jsonEncode((await storage.getHistory()).map((i)=>i.toJson()).toList()),isNot(contains('QA_RELAY_ONLY')));await state.switchToNativeImages();expect(state.settings.imageProvider,'novelai');expect(await storage.getCompatibleImageKey(state.settings.compatibleImage['credentialId']),'QA_RELAY_ONLY');});
 testWidgets('selected NovelAI envelope mounts actual dedicated controls on phone layout',(tester)async{await tester.runAsync(()=>state.saveCompatibleSettings(config(),'QA_RELAY_ONLY'));await tester.pumpWidget(ChangeNotifierProvider.value(value:state,child:const MaterialApp(home:GenerateScreen())));await tester.pumpAndSettle();expect(find.byKey(const ValueKey('compatible-prompt')),findsOneWidget);expect(find.byKey(const ValueKey('compatible-generation-status')),findsOneWidget);expect(tester.takeException(),isNull);await tester.pumpWidget(const SizedBox.shrink());});
}
