import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {stageDownload} from '../stage-download.mjs';
test('stages only pinned metadata, rejects stale embedded runtime and bad hashes',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'agent-download-'));
 const dest=path.join(root,'assets'); const bytes=Buffer.from('synthetic runtime');
 const meta={version:'0.1.2',asset:'agent-rootfs.zip',bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};
 await writeFile(path.join(root,meta.asset),bytes);await writeFile(path.join(root,'seed.json'),JSON.stringify(meta));
 await stageDownload(root,dest);
 assert.deepEqual(await readdir(dest),['seed.json']);
 const staged=JSON.parse(await readFile(path.join(dest,'seed.json')));
 assert.equal(staged.asset,undefined);assert.match(staged.url,/\/agent-v0.1.2\/agent-rootfs.zip$/);
 await writeFile(path.join(dest,'agent-rootfs.zip'),bytes);
 await assert.rejects(stageDownload(root,dest),/embedded rootfs/);
 await writeFile(path.join(root,meta.asset),Buffer.alloc(bytes.length));
 await assert.rejects(stageDownload(root,path.join(root,'other')),/hash mismatch/);
});
