import {useEffect,useRef,useState} from 'react';
import type {AppSettings} from '../types';
import type {AgentDiscoveredModel} from '../agent/types';
import {agentProviderKey,newSavedAgentModel,normalizeSavedAgentModels,selectedAgentModelPatch} from '../agent/model-selections';
import {studioUxText} from '../agent/ux';
import {SelectMenuCompat} from './ui';
export function AgentModelCollection({draft,onChange,disabled}:{draft:Partial<AppSettings>;onChange:(patch:Partial<AppSettings>)=>void;disabled:boolean}) {
  const [found,setFound]=useState<AgentDiscoveredModel[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const sequence=useRef(0),key=agentProviderKey(draft as AppSettings),t=(name:string)=>studioUxText(draft.language,name);
  const all=normalizeSavedAgentModels(draft.savedAgentModels),selected=all.filter(m=>m.providerKey===key);
  useEffect(()=>{sequence.current++;setFound([]);setBusy(false);setMessage('');return()=>{sequence.current++;};},[key,draft.agentApiKey]);
  const setModels=(models:typeof all)=>onChange({savedAgentModels:models});
  const remove=(id:string)=>{const next=all.filter(p=>p.providerKey!==key||p.id!==id);const replacement=next.find(p=>p.providerKey===key);onChange({savedAgentModels:next,...(draft.agentApiModel===id?(replacement?selectedAgentModelPatch(replacement):{agentApiModel:''}):{})});};
  const add=(model:AgentDiscoveredModel)=>{if(selected.some(m=>m.id===model.id))return;const saved=newSavedAgentModel(draft as AppSettings,model);setModels([...all,saved]);if(!draft.agentApiModel)onChange({...selectedAgentModelPatch(saved),savedAgentModels:[...all,saved]});};
  async function discover(){const id=++sequence.current;setBusy(true);setMessage('');try{const result=await window.naiDesktop.discoverAgentModels({protocol:draft.agentApiProtocol!,baseUrl:draft.agentApiBaseUrl??'',apiKey:draft.agentApiKey??'',currentModel:draft.agentApiModel});if(id!==sequence.current)return;if(result.ok){setFound(result.models);setMessage(result.models.length?t('foundModels'):t('emptyModels'));}else setMessage(t('failedModels'));}catch{if(id===sequence.current)setMessage(t('failedModels'));}finally{if(id===sequence.current)setBusy(false);}}
  const filtered=found.filter(m=>`${m.id} ${m.displayName}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="pi-model-collection" aria-label={t('selectedModels')}><div className="pi-model-toolbar"><button disabled={disabled||busy||!draft.agentApiBaseUrl?.trim()} onClick={()=>void discover()}>{t(busy?'statusRunning':'loadModels')}</button><button disabled={disabled||!draft.agentApiModel?.trim()} onClick={()=>add({id:draft.agentApiModel!.trim(),displayName:draft.agentApiModel!.trim(),metadataSource:'unknown'})}>{t('addModel')}</button></div>{message&&<p role="status">{message}</p>}
  {!!found.length&&<><label>{t('searchModels')}<input value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="pi-model-discovery-list">{filtered.slice(0,80).map(m=><label key={m.id}><input type="checkbox" disabled={disabled} checked={selected.some(p=>p.id===m.id)} onChange={e=>e.target.checked?add(m):remove(m.id)}/><span title={m.id}>{m.displayName}<small>{m.id} · {t("modelSource_"+m.metadataSource)}</small></span></label>)}</div>{filtered.length>80&&<small>{t('filterModelsHint')}</small>}</>}
  <h3>{t('selectedModels')}</h3>{selected.map(m=><div className="pi-saved-model" key={m.id}><div className="pi-model-toolbar"><button disabled={disabled} aria-pressed={draft.agentApiModel===m.id} onClick={()=>onChange(selectedAgentModelPatch(m))} title={m.id}>{m.displayName}</button><button disabled={disabled} aria-label={`${t('removeModel')}: ${m.id}`} onClick={()=>remove(m.id)}>{t('removeModel')}</button></div><label>{t('contextWindow')}<input type="number" min={8192} max={2000000} value={m.contextWindow} disabled={disabled} onChange={e=>{const updated={...m,contextWindow:Number(e.target.value)};onChange({savedAgentModels:all.map(p=>p===m?updated:p),...(draft.agentApiModel===m.id?{agentContextWindow:updated.contextWindow}:{})});}}/></label><label>{t('reasoningLevel')}<SelectMenuCompat disabled={disabled} value={m.reasoningEffort} onChange={e=>{const updated={...m,reasoningEffort:e.target.value as typeof m.reasoningEffort};onChange({savedAgentModels:all.map(p=>p===m?updated:p),...(draft.agentApiModel===m.id?{agentReasoningEffort:updated.reasoningEffort}:{})});}}>{['auto','low','medium','high'].map(v=><option key={v} value={v}>{t(`reasoning_${v}`)}</option>)}</SelectMenuCompat></label></div>)}
  </section>;
}
