import { normalizeAppLanguage } from "../i18n";

export type ComparisonStrings = Record<string, string>;

const ZH_CN: ComparisonStrings = {
  intervalMinSeconds: "最短间隔（秒）",
  intervalMaxSeconds: "最长间隔（秒）",
  intervalHint: "每张完成后随机等待，精确到 0.1 秒。两端相同为固定间隔；均为 0 则不等待。修改从下一张完成后生效。",
  waitingInterval: "等待生成间隔中",
  eyebrow: "LANGBAI / 比较实验",
  title: "画师比较",
  subtitle: "固定提示词、模型与种子，保存每轮结果与评价。",
  back: "返回工具",
  allProjectCombinations: "本项目全部组合",
  filterCombinationRun: "按生成轮次筛选（可选）",
  combinationLibraryHint: "当前项目的组合会持续累积在这里，跨日期、跨轮次一起对比。重新生成的图片归入原卡片；不同项目相互独立。",
  artistTasks: "单画师生成进度",
  combinationTasks: "画师组合生成进度",
  resumeOriginalHint: "继续任务沿用原提示词、模型和种子，跳过已完成图片。新条件仅用于新任务或卡片重新生成。",
  generationRecords: "生成记录（参数与历史）",
  recordFilter: "查看生成记录",
  generateMissing: "生成未安排的对象",
  noNewEntries: "所选对象已有生成记录，请继续原任务；需要新图时使用卡片重新生成。",
  combinationHeading: "画师组合",
  visibleEntryCount: "当前显示 {count} 个",
  projectCapacity: "单画师 {artists} 个 · 组合 {recipes} 个",
  skipped: "重复已跳过",
  resumeOriginal: "继续原任务",
  generateNewArtists: "生成新增画师",
  compareTab: "单画师比较",
  exploreTab: "探索画师组合",
  exploreViewTitle: "从单画师评级到画师组合",
  exploreViewHint: "先在“单画师比较”中评级，已评级的单画师会自动进入对应等级的池子。在左侧设置各等级的抽取数量和权重范围，预览组合后勾选生图；组合也可评级和打标签，但不会再次进入单画师池。",
  loading: "正在读取比较项目…",
  project: "比较项目",
  chooseProject: "选择项目",
  createProject: "新建项目",
  renameProject: "重命名",
  renamePlaceholder: "项目名称",
  renameDone: "项目名称已更新",
  entries: "比较对象",
  entriesCount: "{count} 个对象",
  entryInput: "粘贴画师或画师串",
  entryHint: "一行一个对象；逗号只属于当前画师串。支持单画师、配方和 TSV。",
  projectTags: "项目标签",
  projectTagsHint: "用于整理与筛选，不会写入生成提示词。",
  tagName: "标签名称",
  tagNameRequired: "标签名称不能为空。",
  newTagPlaceholder: "新标签名称",
  addTag: "添加标签",
  saveTags: "保存标签目录",
  deleteTag: "删除标签",
  tagLimit: "最多 100 个标签。",
  tagNameTooLong: "标签名称最多 80 个字符。",
  duplicateTag: "标签名称不能重复。",
  chooseTags: "选择标签",
  closeTags: "收起标签",
  tagSearch: "搜索标签",
  noTags: "还没有项目标签",
  noTagResults: "没有匹配的标签",
  noTagsSelected: "未设置标签",
  tagFilter: "标签",
  allTags: "全部标签",
  plainText: "普通文本",
  tsvText: "TSV / Excel",
  nameColumn: "名称列",
  promptColumn: "提示词列",
  noteColumn: "备注列",
  noColumn: "不使用",
  tsvPreview: "列映射预览",
  addEntries: "加入项目",
  noEntries: "还没有比较对象",
  commonConditions: "共同条件",
  positivePrompt: "共同正面提示词",
  negativePrompt: "共同负面提示词",
  model: "模型",
  width: "宽度",
  height: "高度",
  steps: "步数",
  cfg: "CFG",
  seeds: "共同种子",
  seedHint: "用逗号或换行分隔；所有对象使用同一组种子。",
  fixedSeed: "固定种子",
  seedInvalid: "种子必须是 0–4294967295 的整数。",
  seedCountInvalid: "每轮最多使用 10 个共同种子。",
  ratingScheme: "评级方案",
  editRatings: "编辑评级",
  closeEditor: "收起编辑",
  addLevel: "添加档位",
  saveRatings: "保存评级方案",
  ratingName: "档位名称",
  ratingColor: "颜色",
  moveUp: "上移",
  moveDown: "下移",
  deleteLevel: "删除",
  deleteLevelTitle: "删除评级档位",
  deleteLevelHint: "该档位已被使用。请选择将当前项目和历史轮次中的评分映射到哪个档位，或清空评分。",
  clearRatings: "清空相关评分",
  replaceWith: "映射到",
  chooseDeleteTarget: "请选择目标评级或清空评分",
  confirmDelete: "确认删除",
  legacyRatingsTitle: "同步历史评级方案",
  legacyRatingsHint: "历史轮次仍使用已移除的评级档位。请为每个旧档位选择当前档位或未评级；同名档位也不会自动匹配。",
  legacyRatingMap: "历史档位映射",
  chooseRatingMapping: "请选择映射",
  mapToUnrated: "设为未评级",
  syncRatings: "确认同步历史评级",
  syncRatingsRequired: "请为每个历史档位选择映射后再确认。",
  cancel: "取消",
  noRating: "未评级",
  createRun: "创建本轮",
  selectEntriesFirst: "请先选择至少一个比较对象。",
  selected: "已选 {count} 个",
  selectVisible: "选择当前筛选",
  clearSelection: "清空选择",
  run: "实验轮次",
  draftRun: "画师库（已保存）",
  latestRun: "最近一轮",
  runCreated: "任务已创建，请确认费用后开始。",
  runStatus: "状态",
  pending: "待生成",
  running: "生成中",
  idle: "未运行",
  done: "已完成",
  failed: "失败",
  uncertain: "待核对",
  completed: "完成 {done} / {total}",
  quoted: "预计 {amount} Anlas",
  actual: "实扣 {amount} Anlas",
  quoteAndStart: "开始/继续生成",
  quoteFirst: "报价",
  pause: "暂停排队",
  pausing: "当前图片完成后暂停",
  retry: "重试",
  retryUncertain: "确认扣费风险后重试",
  retryWarning: "这次请求可能已经扣费。只有在确认输出不存在后才重试。",
  noRun: "默认显示已保存的画师库；选择历史轮次可查看当轮结果。",
  unfinishedRun: "最近一轮尚未完成",
  unfinishedRunHint: "还有 {pending} 个待生成、{uncertain} 个待核对。请继续已有轮次，不要新建轮次重跑。",
  viewUnfinished: "查看/继续",
  filters: "筛选",
  all: "全部",
  single: "单画师",
  recipe: "配方",
  rated: "评级",
  noteSearch: "搜索备注",
  noteSearchPlaceholder: "例如：适合厚涂",
  sortOriginal: "原始顺序",
  sortRating: "按评级",
  grid: "网格",
  compact: "紧凑",
  expandPrompt: "展开提示词",
  collapsePrompt: "收起提示词",
  copyPrompt: "复制画师串",
  copied: "已复制",
  note: "备注",
  notePlaceholder: "添加长期备注…",
  saveNote: "保存备注",
  autoSaveNotes: "失焦自动保存备注",
  pool: "按评级进入探索池",
  poolEligible: "已按评级入池",
  poolNeedsRating: "未评级，不进入探索池",
  recipeExcluded: "配方不会进入探索池",
  openImage: "查看大图",
  imageMissing: "暂无图片",
  savedImages: "{count} 张已保存",
  cover: "封面",
  noCover: "未设置封面",
  setCover: "设为封面",
  coverSelected: "当前封面",
  removeCover: "移除封面",
  chooseCover: "选择封面",
  regenerate: "仅重生成此卡片 · 1 张",
  regenerateHint: "使用当前共同条件和新随机种子；确认费用后生成，旧图保留。",
  image: "图片",
  imageSeed: "种子",
  previous: "上一项",
  next: "下一项",
  previousPage: "上一页",
  nextPage: "下一页",
  page: "第 {page} 页",
  close: "关闭",
  exploreRules: "探索规则",
  exploreHint: "只从已加入探索池的单画师抽取；配方会作为待生成对象保存。",
  levelCount: "数量",
  minWeight: "最小权重",
  maxWeight: "最大权重",
  recipeCount: "配方数量",
  exploreSeed: "随机种子",
  previewRecipes: "预览配方",
  generateRecipes: "生成已选配方",
  generatedRecipe: "生成的配方",
  noPoolEntries: "请先在比较页勾选单画师并加入探索池。",
  noRecipes: "还没有生成配方预览。",
  exports: "导入与导出",
  exportZip: "完整备份 ZIP",
  exportCsv: "导出表格 CSV",
  exportExcel: "图文表格 Excel",
  exportWorking: "正在准备导出，请选择保存位置。图片将逐张处理，完成后会显示结果。",
  exportExcelHint: "Excel 含等比例压缩预览、评级、标签、备注及生成参数。恢复完整项目请用 ZIP 备份。",
  importProject: "导入备份",
  importHint: "ZIP 包含原图，可恢复项目、评级、标签、备注和生成进度。",
  removeCoverHint: "移除封面只取消封面标记，不会删除原图。",
  error: "操作失败",
  requestFailed: "请求失败，请稍后重试。",
  loadingError: "无法读取比较项目。",
  actionSuccess: "已完成",
  quoteConfirmTitle: "确认本轮费用",
  quoteConfirm: "本轮包含 {jobs} 个任务，预计消耗 {amount} Anlas。确认后才会向 NovelAI 提交生成请求。",
  continueGeneration: "确认并开始",
  budgetExceeded: "报价超过可用额度，已停止继续提交。",
  selectRun: "选择轮次",
  projectEmpty: "新建一个项目开始整理画师。",
  addEntryCount: "已加入 {count} 个对象",
  pauseAll: "暂停当前比较任务",
  onlySingles: "探索仅支持单画师",
  useCurrentParams: "已同步当前生成页参数",
  syncParams: "从生成页同步",
};

const EN_US: ComparisonStrings = {
  intervalMinSeconds: "Minimum interval (seconds)",
  intervalMaxSeconds: "Maximum interval (seconds)",
  intervalHint: "Random wait after each image, in 0.1-second steps. Equal bounds give a fixed delay; both zero disables waiting. Changes apply after the next image completes.",
  waitingInterval: "Waiting between images",
  eyebrow: "LANGBAI / COMPARISON LAB",
  title: "Artist comparison",
  subtitle: "Keep prompts, model, and seeds fixed while you review each run.",
  back: "Back to tools",
  allProjectCombinations: "All combinations in this project",
  filterCombinationRun: "Filter by generation run (optional)",
  combinationLibraryHint: "Combinations accumulate across dates and runs within this project. Regenerated images stay on the original card; projects remain separate.",
  artistTasks: "Artist generation progress",
  combinationTasks: "Combination generation progress",
  resumeOriginalHint: "Resume with the original prompts, model and seeds, skipping completed images. New settings apply to new tasks or card regeneration.",
  generationRecords: "Generation records (settings and history)",
  recordFilter: "View generation record",
  generateMissing: "Generate unscheduled entries",
  noNewEntries: "These entries already have generation records. Resume the existing task or regenerate a card.",
  combinationHeading: "Artist combinations",
  visibleEntryCount: "Showing {count} entries",
  projectCapacity: "Artists: {artists} · Combinations: {recipes}",
  skipped: "Duplicate skipped",
  resumeOriginal: "Resume original task",
  generateNewArtists: "Generate new artists",
  compareTab: "Compare artists",
  exploreTab: "Explore artist combinations",
  exploreViewTitle: "Generated recipes",
  exploreViewHint: "Rate individual artists first to add them to their rating pools. Set counts and weight ranges on the left, preview combinations, then select which to generate. Combinations can be rated and tagged but never enter the individual artist pools.",
  loading: "Loading comparison projects…",
  project: "Comparison project",
  chooseProject: "Choose project",
  createProject: "New project",
  renameProject: "Rename",
  renamePlaceholder: "Project name",
  renameDone: "Project name updated",
  entries: "Comparison entries",
  entriesCount: "{count} entries",
  entryInput: "Paste artists or artist strings",
  entryHint: "One entry per line. Commas stay inside an artist string. Single artists, recipes, and TSV are supported.",
  projectTags: "Project tags",
  projectTagsHint: "For organising and filtering only; tags never enter generation prompts.",
  tagName: "Tag name",
  tagNameRequired: "Tag name cannot be empty.",
  newTagPlaceholder: "New tag name",
  addTag: "Add tag",
  saveTags: "Save tag directory",
  deleteTag: "Delete tag",
  tagLimit: "A project can have up to 100 tags.",
  tagNameTooLong: "Tag names can be at most 80 characters.",
  duplicateTag: "Tag names must be unique.",
  chooseTags: "Choose tags",
  closeTags: "Close tags",
  tagSearch: "Search tags",
  noTags: "No project tags yet",
  noTagResults: "No matching tags",
  noTagsSelected: "No tags",
  tagFilter: "Tag",
  allTags: "All tags",
  plainText: "Plain text",
  tsvText: "TSV / Excel",
  nameColumn: "Name column",
  promptColumn: "Prompt column",
  noteColumn: "Note column",
  noColumn: "Do not use",
  tsvPreview: "Column mapping preview",
  addEntries: "Add to project",
  noEntries: "No comparison entries yet",
  commonConditions: "Shared conditions",
  positivePrompt: "Shared positive prompt",
  negativePrompt: "Shared negative prompt",
  model: "Model",
  width: "Width",
  height: "Height",
  steps: "Steps",
  cfg: "CFG",
  seeds: "Shared seeds",
  seedHint: "Separate seeds with commas or new lines. Every entry uses the same set.",
  fixedSeed: "Fixed seeds",
  seedInvalid: "Seeds must be integers from 0 to 4294967295.",
  seedCountInvalid: "A run can use at most 10 shared seeds.",
  ratingScheme: "Rating scheme",
  editRatings: "Edit ratings",
  closeEditor: "Close editor",
  addLevel: "Add level",
  saveRatings: "Save rating scheme",
  ratingName: "Level name",
  ratingColor: "Color",
  moveUp: "Move up",
  moveDown: "Move down",
  deleteLevel: "Delete",
  deleteLevelTitle: "Delete rating level",
  deleteLevelHint: "This level is in use. Map ratings in the current project and historical runs to another level or clear them.",
  clearRatings: "Clear related ratings",
  replaceWith: "Map to",
  chooseDeleteTarget: "Choose a target level or clear ratings",
  confirmDelete: "Delete level",
  legacyRatingsTitle: "Sync historical rating scheme",
  legacyRatingsHint: "Historical runs still use rating levels that were removed from this project. Choose a current level or unrated for every old level; same names are never matched automatically.",
  legacyRatingMap: "Historical level mapping",
  chooseRatingMapping: "Choose a mapping",
  mapToUnrated: "Set as unrated",
  syncRatings: "Sync historical ratings",
  syncRatingsRequired: "Choose a mapping for every historical level before confirming.",
  cancel: "Cancel",
  noRating: "Unrated",
  createRun: "Create run",
  selectEntriesFirst: "Select at least one comparison entry first.",
  selected: "{count} selected",
  selectVisible: "Select filtered",
  clearSelection: "Clear selection",
  run: "Run",
  draftRun: "Artist library (saved)",
  latestRun: "Latest run",
  runCreated: "Run created. Confirm its quote before starting.",
  runStatus: "Status",
  pending: "Pending",
  running: "Running",
  idle: "Idle",
  done: "Done",
  failed: "Failed",
  uncertain: "Needs review",
  completed: "{done} / {total} complete",
  quoted: "Estimated {amount} Anlas",
  actual: "Spent {amount} Anlas",
  quoteAndStart: "Start or continue generation",
  quoteFirst: "Quote",
  pause: "Pause queue",
  pausing: "Pausing after current image",
  retry: "Retry",
  retryUncertain: "Acknowledge charge risk and retry",
  retryWarning: "This request may already have been charged. Retry only after checking that no output exists.",
  noRun: "The saved artist library is shown by default; choose a history run to inspect its results.",
  unfinishedRun: "The latest run is unfinished",
  unfinishedRunHint: "{pending} pending and {uncertain} need review. Continue this run instead of creating a duplicate.",
  viewUnfinished: "View / continue",
  filters: "Filters",
  all: "All",
  single: "Single",
  recipe: "Recipe",
  rated: "Rating",
  noteSearch: "Search notes",
  noteSearchPlaceholder: "e.g. painterly",
  sortOriginal: "Original order",
  sortRating: "By rating",
  grid: "Grid",
  compact: "Compact",
  expandPrompt: "Expand prompt",
  collapsePrompt: "Collapse prompt",
  copyPrompt: "Copy artist string",
  copied: "Copied",
  note: "Notes",
  notePlaceholder: "Add a long-term note…",
  saveNote: "Save note",
  autoSaveNotes: "Save notes on blur",
  pool: "Enter pool by rating",
  poolEligible: "In pool by rating",
  poolNeedsRating: "Unrated; excluded from pool",
  recipeExcluded: "Recipes cannot enter the exploration pool",
  openImage: "Open large preview",
  imageMissing: "No image yet",
  savedImages: "{count} saved",
  cover: "Cover",
  noCover: "No cover set",
  setCover: "Set as cover",
  coverSelected: "Current cover",
  removeCover: "Remove cover",
  chooseCover: "Choose cover",
  regenerate: "Regenerate this card · 1 image",
  regenerateHint: "Uses current shared settings and a new random seed. Confirm cost before generating; previous images are kept.",
  image: "Image",
  imageSeed: "Seed",
  previous: "Previous",
  next: "Next",
  previousPage: "Previous page",
  nextPage: "Next page",
  page: "Page {page}",
  close: "Close",
  exploreRules: "Exploration rules",
  exploreHint: "Sample only single artists in the exploration pool; recipes are saved as pending entries.",
  levelCount: "Count",
  minWeight: "Min weight",
  maxWeight: "Max weight",
  recipeCount: "Recipe count",
  exploreSeed: "RNG seed",
  previewRecipes: "Preview recipes",
  generateRecipes: "Generate selected recipes",
  generatedRecipe: "Generated recipe",
  noPoolEntries: "Add single artists to the exploration pool on the Compare tab first.",
  noRecipes: "No recipe previews yet.",
  exports: "Import and export",
  exportZip: "Full backup ZIP",
  exportCsv: "Export table CSV",
  exportExcel: "Illustrated Excel",
  exportWorking: "Preparing export. Choose a destination; previews are processed one at a time and completion will be reported.",
  exportExcelHint: "Excel includes proportional previews, ratings, tags, notes and generation settings. Use ZIP for a complete restorable backup.",
  importProject: "Import backup",
  importHint: "A full backup restores projects, ratings, runs, and image references.",
  removeCoverHint: "Removing a cover only clears its marker; original images stay safe.",
  error: "Action failed",
  requestFailed: "Request failed. Please try again.",
  loadingError: "Could not load comparison projects.",
  actionSuccess: "Done",
  quoteConfirmTitle: "Confirm run cost",
  quoteConfirm: "This run contains {jobs} jobs and is estimated at {amount} Anlas. Generation is submitted only after confirmation.",
  continueGeneration: "Confirm and start",
  budgetExceeded: "The quote exceeded the approved budget; submission stopped.",
  selectRun: "Select run",
  projectEmpty: "Create a project to start organising artists.",
  addEntryCount: "Added {count} entries",
  pauseAll: "Pause current comparison job",
  onlySingles: "Exploration supports single artists only",
  useCurrentParams: "Synced with current generation parameters",
  syncParams: "Sync from generation",
};

function format(value: string, variables: Record<string, unknown>) {
  return value.replace(/\{(\w+)\}/g, (_, key: string) => String(variables[key] ?? ""));
}

/** Comparison-specific copy with English fallback for unsupported locales. */
export function getComparisonText(language: unknown): ComparisonStrings {
  const locale = normalizeAppLanguage(language);
  return locale === "zh-CN" ? ZH_CN : EN_US;
}

export function formatComparisonText(
  language: unknown,
  key: string,
  variables: Record<string, unknown>,
) {
  return format(getComparisonText(language)[key] ?? EN_US[key] ?? key, variables);
}
