import {it,expect,vi} from 'vitest';
import {createComicGenerationQueue} from './generation-queue';
import {createComicProjectStore} from './project-store';
import {createTagComicPanel} from './tag-comic';
import {DEFAULT_PARAMS,type ComicImageService,type GenerateResult,type TagComicGenerateRequest} from '../types';
function fixture(){
 const values=new Map<string,string>(),storage={getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v);}};
 const store=createComicProjectStore({storage,params:()=>DEFAULT_PARAMS});store.update(p=>({...p,panels:[createTagComicPanel('forest',1),createTagComicPanel('sea',2)]}));
 let n=0;const deps={store,storage,hasToken:vi.fn(async()=>{throw Error('must not read native credentials');}),prepareService:vi.fn(async(_requests:TagComicGenerateRequest[]):Promise<ComicImageService>=>({binding:'host-binding',provider:'openai-images',model:'test/model',size:'auto'})),quote:vi.fn(async()=>null),generate:vi.fn(async(request:TagComicGenerateRequest):Promise<GenerateResult>=>{expect(request.imageServiceBinding).toBe('host-binding');return {ok:true,message:'saved',items:[{id:String(++n),filePath:'saved.png',fileUrl:'fixture://image',date:'today',createdAt:'today',groupId:'g',params:DEFAULT_PARAMS,actualSeed:-1,model:'test/model',generationProvider:'openai-images',width:8,height:6}]};}),cancel:vi.fn(async()=>{})};
 const queue=createComicGenerationQueue(deps);const tasks=store.read().project.panels.flatMap(p=>Array.from({length:6},(_,ordinal)=>({panelId:p.id,ordinal})));
 return {deps,queue,tasks,store,launch:(confirm:(summary:unknown)=>Promise<boolean>=async()=>true)=>queue.launch(tasks,{expectedRevision:store.read().revision,confirm})};
}
it('preflights twelve requests once and confirms the entire compatible batch once without native token lookup',async()=>{const f=fixture(),confirm=vi.fn(async(_summary:unknown)=>true);f.launch(confirm);await f.queue.settled();expect(f.deps.prepareService).toHaveBeenCalledOnce();expect(f.deps.prepareService.mock.calls[0][0]).toHaveLength(12);expect(f.deps.hasToken).not.toHaveBeenCalled();expect(confirm).toHaveBeenCalledOnce();expect(confirm.mock.calls[0][0]).toMatchObject({count:12,quote:null,imageProvider:'openai-images',model:'test/model',size:'auto'});expect(f.deps.generate).toHaveBeenCalledTimes(12);expect(f.queue.getSnapshot().phase).toBe('completed');});
it('later invalid panel preflight stops the whole batch before approval or any POST',async()=>{const f=fixture(),confirm=vi.fn(async(_summary:unknown)=>true);f.deps.prepareService.mockRejectedValueOnce(Error('panel 2 unsupported reference'));f.launch(confirm);await f.queue.settled();expect(confirm).not.toHaveBeenCalled();expect(f.deps.generate).not.toHaveBeenCalled();expect(f.queue.getSnapshot().phase).toBe('failed');});
it('approval denial and cancellation during preflight do not submit images',async()=>{const f=fixture();f.launch(vi.fn(async()=>false));await f.queue.settled();expect(f.deps.generate).not.toHaveBeenCalled();let release!:(v:ComicImageService)=>void;f.deps.prepareService.mockImplementationOnce(()=>new Promise(r=>{release=r;}));f.launch();await f.queue.stop();await f.queue.settled();release({binding:'stale',provider:'openai-images'});expect(f.deps.generate).not.toHaveBeenCalled();expect(f.queue.getSnapshot().phase).toBe('cancelled');});
it('Agent preview carries fee-provider data but does not expose the host HMAC or submit',async()=>{const f=fixture();expect(await f.queue.preview(f.tasks,f.store.read().revision)).toEqual({count:12,quote:null,imageProvider:'openai-images',model:'test/model',size:'auto'});expect(f.deps.hasToken).not.toHaveBeenCalled();expect(f.deps.generate).not.toHaveBeenCalled();});
