import {expect,it,vi} from 'vitest';
import {createComicGenerationQueue,COMIC_RUN_KEY,prepareComicTasks,selectComicTasks} from './generation-queue';
import {createComicProjectStore} from './project-store';
import {createTagComicPanel,TAG_COMIC_STORAGE_KEY} from './tag-comic';
import {DEFAULT_PARAMS,type GenerateResult,type TagComicGenerateRequest} from '../types';
function deferred<T>(){let resolve!:(x:T)=>void;const promise=new Promise<T>(r=>resolve=r);return {promise,resolve};}
function fixture(){
 const values=new Map<string,string>(),storage={getItem:(k:string)=>values.get(k)??null,setItem:vi.fn((k:string,v:string)=>{values.set(k,v);})};
 const store=createComicProjectStore({storage,params:()=>DEFAULT_PARAMS});store.update(p=>({...p,panels:[createTagComicPanel('forest',1),createTagComicPanel('sea',2)]}));
 const result=(id='image',ok=true):GenerateResult=>({ok,message:ok?'saved':'partial',items:[{id,filePath:id+'.png',fileUrl:'fixture://'+id,date:'today',createdAt:'today',groupId:'g',params:DEFAULT_PARAMS,actualSeed:1,model:'fixture',width:1,height:1}]});
 let n=0;const deps={store,storage,hasToken:vi.fn(async()=>true),quote:vi.fn(async()=>4 as number|null),generate:vi.fn(async(_request:TagComicGenerateRequest)=>result('image-'+ ++n)),cancel:vi.fn(async()=>{}),afterSaved:vi.fn(async()=>{})};
 const queue=createComicGenerationQueue(deps),tasks=store.read().project.panels.map(p=>({panelId:p.id,ordinal:0}));
 const launch=(confirm=vi.fn(async()=>true))=>queue.launch(tasks,{expectedRevision:store.read().revision,confirm});
 return {values,storage,store,result,deps,queue,tasks,launch};
}
it('executes one application queue without mounted listeners, persists every candidate and group',async()=>{
 const f=fixture(),listener=vi.fn(),unsubscribe=f.queue.subscribe(listener);unsubscribe();const receipt=f.launch();expect(receipt.total).toBe(2);expect(f.store.read().busy).toBe(true);await f.queue.settled();expect(f.deps.generate).toHaveBeenCalledTimes(2);expect(f.deps.generate.mock.calls[1][0].historyGroupId).toBe('g');expect(f.store.read().project.panels.map(p=>p.candidates.length)).toEqual([1,1]);expect(f.queue.getSnapshot()).toMatchObject({phase:'completed',done:2});expect(f.store.read().busy).toBe(false);expect(listener).not.toHaveBeenCalled();
});
it('rejects duplicate launch while confirmation or generation is pending',async()=>{const f=fixture(),gate=deferred<boolean>();f.launch(vi.fn(()=>gate.promise));await vi.waitFor(()=>expect(f.queue.getSnapshot().phase).toBe('confirming'));expect(()=>f.launch()).toThrow('正在运行');gate.resolve(true);await f.queue.settled();expect(f.deps.generate).toHaveBeenCalledTimes(2);});
it('approval-time project edit is never silently charged using old settings',async()=>{const f=fixture();f.launch(vi.fn(async()=>{f.store.update(p=>({...p,title:'changed'}));return true;}));await f.queue.settled();expect(f.queue.getSnapshot().phase).toBe('failed');expect(f.queue.getSnapshot().error).toContain('已变化');expect(f.deps.generate).not.toHaveBeenCalled();});
it('queue captures immutable per-panel prompts and parameters; later UI drafts affect only a future run',async()=>{const f=fixture();f.deps.afterSaved.mockImplementationOnce(async()=>{f.store.update(p=>({...p,globalStylePrompt:'new style',panels:p.panels.map(x=>({...x,prompt:'new draft'}))}));});f.launch();await f.queue.settled();expect(f.deps.generate.mock.calls[1][0].panelPrompt).toBe('sea');expect(f.deps.generate.mock.calls[1][0].globalStylePrompt).not.toBe('new style');});
it('missing panels and duplicate task identities reject before a journal or native call',()=>{const f=fixture();expect(()=>prepareComicTasks(f.store.read().project,[{panelId:'missing',ordinal:0}])).toThrow('不存在');expect(()=>prepareComicTasks(f.store.read().project,[f.tasks[0],f.tasks[0]])).toThrow('重复');expect(f.values.has(COMIC_RUN_KEY)).toBe(false);expect(f.deps.generate).not.toHaveBeenCalled();});
it('partial native response preserves actual output and stops later tasks',async()=>{const f=fixture();f.deps.generate.mockResolvedValueOnce(f.result('partial',false));f.launch();await f.queue.settled();expect(f.deps.generate).toHaveBeenCalledTimes(1);expect(f.store.read().project.panels[0].candidates[0].historyItemId).toBe('partial');expect(f.queue.getSnapshot()).toMatchObject({phase:'failed',error:'partial'});});
it('stop waits for owned in-flight request, retains late image and never starts next panel',async()=>{const f=fixture(),gate=deferred<GenerateResult>();f.deps.generate.mockImplementationOnce(()=>gate.promise);f.launch();await vi.waitFor(()=>expect(f.deps.generate).toHaveBeenCalledTimes(1));await f.queue.stop();await f.queue.stop();expect(f.deps.cancel).toHaveBeenCalledTimes(1);expect(f.store.read().busy).toBe(true);expect(()=>f.launch()).toThrow();gate.resolve(f.result('late'));await f.queue.settled();expect(f.queue.getSnapshot().phase).toBe('cancelled');expect(f.store.read().project.panels[0].candidates[0].historyItemId).toBe('late');expect(f.deps.generate).toHaveBeenCalledTimes(1);expect(f.store.read().busy).toBe(false);});
it('stop during a stalled quote releases queue without cancelling unrelated native generation',async()=>{const f=fixture(),gate=deferred<number|null>();f.deps.quote.mockImplementation(()=>gate.promise);f.launch();await vi.waitFor(()=>expect(f.deps.quote).toHaveBeenCalledTimes(1));await f.queue.stop();await f.queue.settled();expect(f.queue.getSnapshot().phase).toBe('cancelled');expect(f.deps.cancel).not.toHaveBeenCalled();gate.resolve(10);await Promise.resolve();expect(f.deps.generate).not.toHaveBeenCalled();});
it('stop during a stalled confirmation prevents a late approval from generating',async()=>{const f=fixture(),gate=deferred<boolean>();f.launch(vi.fn(()=>gate.promise));await vi.waitFor(()=>expect(f.queue.getSnapshot().phase).toBe('confirming'));await f.queue.stop();await f.queue.settled();gate.resolve(true);await Promise.resolve();expect(f.queue.getSnapshot().phase).toBe('cancelled');expect(f.deps.generate).not.toHaveBeenCalled();});
it('restart marks a durable in-flight receipt interrupted, never automatically replays paid work',()=>{const f=fixture();f.storage.setItem(COMIC_RUN_KEY,JSON.stringify({id:'previous',projectId:f.store.read().project.id,phase:'running',total:2,done:1,inFlightPanelId:f.tasks[1].panelId}));const restored=createComicGenerationQueue(f.deps);expect(restored.getSnapshot()).toMatchObject({phase:'interrupted',done:1,inFlightPanelId:null});expect(JSON.parse(f.values.get(COMIC_RUN_KEY)!).phase).toBe('interrupted');expect(f.deps.generate).not.toHaveBeenCalled();});
it('corrupt journal is retained and does not cause automatic overwrite/retry',()=>{const f=fixture();f.storage.setItem(COMIC_RUN_KEY,'broken');const q=createComicGenerationQueue(f.deps);expect(()=>q.launch(f.tasks,{expectedRevision:f.store.read().revision,confirm:async()=>true})).toThrow();expect(f.values.get(COMIC_RUN_KEY)).toBe('broken');expect(f.deps.generate).not.toHaveBeenCalled();});
it('failure persisting the initial operation receipt stops before token, quote or charge',()=>{const f=fixture();f.storage.setItem.mockImplementation(()=>{throw Error('disk');});expect(()=>f.launch()).toThrow('disk');expect(f.deps.hasToken).not.toHaveBeenCalled();expect(f.store.read().busy).toBe(false);});
it('project persistence failure after saved image halts queue and does not invent an attached candidate',async()=>{const f=fixture();f.deps.generate.mockImplementationOnce(async()=>{f.storage.setItem.mockImplementation((k,v)=>{if(k===TAG_COMIC_STORAGE_KEY)throw Error('quota');f.values.set(k,v);});return f.result();});f.launch();await f.queue.settled();expect(f.deps.generate).toHaveBeenCalledTimes(1);expect(f.queue.getSnapshot()).toMatchObject({phase:'failed',error:'quota'});expect(f.store.read().project.panels[0].candidates).toEqual([]);expect(f.store.read().busy).toBe(false);});
it('after-save failure cannot erase saved output or retry the charged request',async()=>{const f=fixture();f.deps.afterSaved.mockRejectedValueOnce(Error('refresh/storage failed'));f.launch();await f.queue.settled();expect(f.deps.generate).toHaveBeenCalledTimes(1);expect(f.store.read().project.panels[0].candidates).toHaveLength(1);expect(f.queue.getSnapshot().phase).toBe('failed');});
it('post-generation journal failure still retains project candidate and stops further paid work',async()=>{const f=fixture();f.deps.generate.mockImplementationOnce(async()=>{f.storage.setItem.mockImplementation((k,v)=>{if(k===COMIC_RUN_KEY)throw Error('journal full');f.values.set(k,v);});return f.result();});f.launch();await f.queue.settled();expect(f.store.read().project.panels[0].candidates).toHaveLength(1);expect(f.queue.getSnapshot()).toMatchObject({phase:'failed',error:'journal full'});expect(f.deps.generate).toHaveBeenCalledTimes(1);});
it('native exceptions mark failed panel, release busy and stop the remainder',async()=>{const f=fixture();f.deps.generate.mockRejectedValueOnce(Error('network'));f.launch();await f.queue.settled();expect(f.store.read().project.panels[0].status).toBe('failed');expect(f.queue.getSnapshot()).toMatchObject({phase:'failed',error:'network'});expect(f.deps.generate).toHaveBeenCalledTimes(1);expect(f.store.read().busy).toBe(false);});
it('invalid quote and absent token stop before approval or generation',async()=>{const f=fixture(),confirm=vi.fn(async()=>true);f.deps.quote.mockResolvedValueOnce(NaN);f.launch(confirm);await f.queue.settled();expect(confirm).not.toHaveBeenCalled();f.deps.hasToken.mockResolvedValueOnce(false);f.launch(confirm);await f.queue.settled();expect(confirm).not.toHaveBeenCalled();expect(f.deps.generate).not.toHaveBeenCalled();});
it('denial does not spend and preserves the project candidates',async()=>{const f=fixture();f.launch(vi.fn(async()=>false));await f.queue.settled();expect(f.queue.getSnapshot().phase).toBe('cancelled');expect(f.deps.generate).not.toHaveBeenCalled();expect(f.store.read().busy).toBe(false);});
it('stale run cancellation cannot stop a newer queue',async()=>{const f=fixture(),gate=deferred<boolean>();const receipt=f.launch(vi.fn(()=>gate.promise));await expect(f.queue.stop('old-run')).rejects.toThrow('runId');expect(f.queue.active).toBe(true);await f.queue.stop(receipt.id);await f.queue.settled();expect(f.queue.getSnapshot().phase).toBe('cancelled');expect(f.deps.cancel).not.toHaveBeenCalled();});

it('Agent planning selects all or explicit panels and preserves the three existing UI generation modes',async()=>{
 const f=fixture();await f.launch();await f.queue.settled();const p=f.store.read().project;p.initialGenerationCount=2;
 expect(selectComicTasks(p,'initial',[])).toHaveLength(2);expect(selectComicTasks(p,'regenerate',[])).toHaveLength(4);expect(selectComicTasks(p,'additional',[p.panels[1].id])).toEqual([{panelId:p.panels[1].id,ordinal:0}]);
 expect(()=>selectComicTasks(p,'unknown',[])).toThrow();expect(()=>selectComicTasks(p,'initial',['missing'])).toThrow();expect(()=>selectComicTasks(p,'initial',[p.panels[0].id,p.panels[0].id])).toThrow();
});
it('preview cannot charge, accepts unknown cost and rejects estimate-time revision drift',async()=>{
 const f=fixture();f.deps.quote.mockResolvedValueOnce(null);expect(await f.queue.preview(f.tasks,f.store.read().revision)).toEqual({count:2,quote:null});expect(f.deps.generate).not.toHaveBeenCalled();
 f.deps.quote.mockImplementationOnce(async()=>{f.store.update(p=>({...p,title:'changed'}));return 4;});await expect(f.queue.preview(f.tasks,f.store.read().revision)).rejects.toThrow('已变化');
});
it('host run identity is preserved and cannot reuse the latest receipt or observe another run',async()=>{
 const f=fixture();f.queue.launch(f.tasks,{runId:'agent-comic-test',expectedRevision:f.store.read().revision,confirm:async()=>true});expect((await f.queue.wait('agent-comic-test')).phase).toBe('completed');
 await expect(f.queue.wait('wrong')).rejects.toThrow();expect(()=>f.queue.launch(f.tasks,{runId:'agent-comic-test',expectedRevision:f.store.read().revision,confirm:async()=>true})).toThrow('已经使用');
});
