const categoryLabels={tavernAgent:'酒馆 Agent',styleLab:'画风实验室',configuration:'软件配置',apiCredentials:'API 凭据（含密钥）',artistLibrary:'画师与收藏',textHistory:'提示词历史',referencePresets:'参考图预设',imageHistory:'图片与生成历史',promptPresets:'提示词与风格预设',agentWorkspace:'角色与对话资料',workspaceData:'工具项目',characters:'角色卡',personas:'用户人设',lorebooks:'世界书',samplerPresets:'采样预设',styles:'风格预设',positivePresets:'正面提示词预设'};
export function approvalSummary(pending){
 const p=pending.parameters??{};
 if(p.templateWorkflow)return {title:'确认本次模板生图任务',description:'一次确认包含提示词转换、最多两次格式校正，以及所列张数的生图；可能产生模型费用和 Anlas 消耗。校验失败会停止，不重复弹确认。',target:p.description??'',confirm:'确认本次任务'};
 if(pending.tool==='studio_material_confirm')return {title:'应用本机资料到当前会话',description:'创建或复用酒馆副本，再绑定当前会话；原本机资料与其他会话保持不变。'+(Array.isArray(p.warnings)?p.warnings.join('；'):''),target:[categoryLabels[p.collection],p.name].filter(Boolean).join(' · '),confirm:'确认应用'};
 if(pending.tool==='langbai_templates')return {title:p.action==='restore'?'恢复内置提示词模板':'保存软件提示词模板',description:'执行前备份配置；仅修改所选用途、版本和模式，不生成图片。',target:[p.kind==='reverse'?'图片反推':'提示词转换',p.templateVersion,{mixed:'混合模式',tags:'标签模式',natural:'自然语言'}[p.mode]].filter(Boolean).join(' · '),confirm:p.action==='restore'?'确认恢复':'确认保存'};
 if(pending.tool==='langbai_api')return {title:p.action==='clearCredential'?'清除 API 凭据':'保存 API 配置',description:p.action==='clearCredential'?'清除后相关服务需要重新填写凭据；不会删除对话或图片。':'现有凭据将用于本次设置的服务地址。请核对地址；保存不会自动调用收费接口。',target:[p['名称'],p['修改']?.baseUrl,p['修改']?.imageUrl].filter(Boolean).join(' · '),confirm:p.action==='clearCredential'?'确认清除':'确认保存'};
 if(pending.tool==='langbai_backup')return {title:p.action==='restore'?'恢复所选备份':'导出含凭据的备份',description:p.action==='restore'?'先保存恢复前备份，再合并所选资料；所选配置会覆盖，设备路径保留。':'文件只保存到本机，不上传；包含密钥，请妥善保存。',target:p['备份']??'',categories:Array.isArray(p.categories)?p.categories.map(x=>categoryLabels[x]??x).join('、'):'',confirm:p.action==='restore'?'确认恢复':'确认备份'};
 if(pending.tool==='langbai_library')return {title:p.action==='delete'?'删除所选资料':'保存资料修改',description:'执行前创建可恢复备份。保留图片文件，不自动生成图片。',target:[categoryLabels[p.collection]??p.collection,p['名称']??p.id].filter(Boolean).join(' · '),confirm:p.action==='delete'?'确认删除':'确认保存'};
 if(pending.tool==='langbai_tasks')return {title:p.action==='resume'?'继续生成队列':'移除排队任务',description:p.action==='resume'?'继续执行尚未完成的排队任务，可能消耗 Anlas。':'仅移除待执行任务，已生成的图片保留。',target:p.id??'',confirm:p.action==='resume'?'确认继续':'确认移除'};
 return {title:pending.title??'确认软件操作',description:pending.kind==='operation'?'请检查本次操作内容。确认后执行一次，软件不再重复确认。':`当前会话请求 ${pending.count} 张图片处理任务，可能消耗 Anlas。`,target:'',confirm:pending.kind==='operation'?'确认执行':'确认生成'};
}
