const categoryLabels={tavernAgent:'酒馆 Agent',styleLab:'画风实验室',configuration:'软件配置',apiCredentials:'API 凭据（含密钥）',artistLibrary:'画师与收藏',textHistory:'提示词历史',referencePresets:'参考图预设',imageHistory:'图片与生成历史',promptPresets:'提示词与风格预设',agentWorkspace:'角色与对话资料',workspaceData:'工具项目',characters:'角色卡',personas:'用户人设',lorebooks:'世界书',samplerPresets:'采样预设',styles:'风格预设',positivePresets:'正面提示词预设'};
export function approvalSummary(pending){
 const p=pending.parameters??{};
 if(pending.tool==='langbai_software_action'&&['comic.generation.start','batch.generation.start'].includes(p.action)){
  const count=p.plannedImages??p.count;
  return {title:p.action==='batch.generation.start'?'确认批量重绘':'确认漫画整批生图',description:p.imageProvider==='openai-images'?'本次确认覆盖整批兼容图片服务生成，费用以服务商为准；软件不会再次逐张确认。失败会停止后续提交，已生成图片保留。':'本次确认覆盖整批图片生成，可能消耗 Anlas；软件不会再次逐张确认。失败会停止后续提交，已生成图片保留。',target:[p.imageProvider==='openai-images'?p.model:null,p.imageProvider==='openai-images'?p.size:null,p.projectTitle,(p.action==='batch.generation.start'?{all:'所选图片全部重绘',pending:'未完成图片',failed:'失败图片',additional:'每图追加一张'}:{initial:'补足初始候选',regenerate:'重做候选',additional:'每格追加一张'})[p.mode],Number.isSafeInteger(count)&&count>0?`${count} 张图片`:'请核对计划张数',p.imageProvider!=='openai-images'&&Number.isFinite(p.estimatedAnlas)?`预估 ${p.estimatedAnlas} Anlas`:null].filter(Boolean).join(' · '),confirm:'确认本批生成'};
 }
 if(pending.tool==='langbai_software_action'&&['comic.project.new','comic.project.import','comic.panels.replace','comic.panels.remove'].includes(p.action))return {title:p.title??'修改漫画工程',description:'本次修改前保存工程快照；已有图片文件保留，不重新生成。确认后替换对应工程或分镜记录。',target:p.id??'当前漫画工程',confirm:'确认修改工程'};
 if(pending.tool==='langbai_software_action'&&['favorites.local.remove','favorites.online.remove'].includes(p.action))return {title:'移出收藏',description:p.action==='favorites.local.remove'?'只移除收藏记录，原图和收藏目录中的图片都保留。':'只移除在线书签，不影响本地收藏和生成图片。',target:p.id??'',confirm:'确认移出收藏'};
 if(pending.tool==='langbai_software_action'&&p.action==='navigation.reset')return {title:'恢复顶栏默认顺序',description:'只恢复功能标签排列，不删除收藏、图片、参数或对话。',target:'软件顶栏',confirm:'恢复默认顺序'};
 if(pending.tool==='langbai_software_action'&&p.action==='app.update.install'&&p.platform==='android')return {title:'更新 Android 软件',description:'一次确认包括下载、完整性校验、停止当前 Agent 和安装交接。对话和图片保留；Android 系统可能要求安装权限或确认。打开安装器不代表更新成功，重新打开软件后核对版本。',target:[`${p.currentVersion??''} → ${p.version??''}`,Number.isFinite(p.downloadBytes)?`${(p.downloadBytes/1048576).toFixed(1)} MiB`:null,p.sourceUrl].filter(Boolean).join(' · '),confirm:'确认更新软件'};
 if(pending.tool==='langbai_software_action'&&p.action==='app.update.install')return {title:'更新软件并自动重启',description:'一次确认包括下载、完整性校验、停止当前任务和安装重启。对话和图片保留；安装程序启动不等于更新完成，重启后核对版本。',target:[`${p.currentVersion??''} → ${p.version??''}`,Number.isFinite(p.downloadBytes)?`${(p.downloadBytes/1048576).toFixed(1)} MiB`:null,p.sourceUrl].filter(Boolean).join(' · '),confirm:'确认更新并重启'};
 if(pending.tool==='langbai_software_action'&&String(p.action).startsWith('resources.')){
  const r=p.resource??{},download=p.action==='resources.download',remove=p.action==='resources.delete';
  return {title:download?'下载并安装资源数据库':remove?'删除本机资源数据库':'恢复上一版资源数据库',description:(download?'将下载并验证完整性，再替换数据库；旧版保留用于恢复。':remove?'删除此资源数据库、旧版与下载断点。':'用已保留的旧版替换当前资源数据库。')+' 不改动图片、角色、预设或对话。',target:[r.label??p.id,download&&Number.isFinite(r.downloadBytes)?`${(r.downloadBytes/1048576).toFixed(1)} MiB`:null,r.sourceUrl,r.license].filter(Boolean).join(' · '),confirm:download?'确认下载安装':remove?'确认删除':'确认恢复'};
 }
 if(p.templateWorkflow)return {title:'确认本次模板生图任务',description:'一次确认包含提示词转换、最多两次格式校正，以及所列张数的生图；可能产生模型费用和 Anlas 消耗。校验失败会停止，不重复弹确认。',target:p.description??'',confirm:'确认本次任务'};
 if(pending.tool==='studio_material_confirm')return {title:'应用本机资料到当前会话',description:'创建或复用酒馆副本，再绑定当前会话；原本机资料与其他会话保持不变。'+(Array.isArray(p.warnings)?p.warnings.join('；'):''),target:[categoryLabels[p.collection],p.name].filter(Boolean).join(' · '),confirm:'确认应用'};
 if(pending.tool==='langbai_templates')return {title:p.action==='restore'?'恢复内置提示词模板':'保存软件提示词模板',description:'执行前备份配置；仅修改所选用途、版本和模式，不生成图片。',target:[p.kind==='reverse'?'图片反推':'提示词转换',p.templateVersion,{mixed:'混合模式',tags:'标签模式',natural:'自然语言'}[p.mode]].filter(Boolean).join(' · '),confirm:p.action==='restore'?'确认恢复':'确认保存'};
 if(pending.tool==='langbai_api')return {title:p.action==='clearCredential'?'清除 API 凭据':'保存 API 配置',description:p.action==='clearCredential'?'清除后相关服务需要重新填写凭据；不会删除对话或图片。':'现有凭据将用于本次设置的服务地址。请核对地址；保存不会自动调用收费接口。',target:[p['名称'],p['修改']?.baseUrl,p['修改']?.imageUrl].filter(Boolean).join(' · '),confirm:p.action==='clearCredential'?'确认清除':'确认保存'};
 if(pending.tool==='langbai_backup')return {title:p.action==='restore'?'恢复所选备份':'导出含凭据的备份',description:p.action==='restore'?'先保存恢复前备份，再合并所选资料；所选配置会覆盖，设备路径保留。':'文件只保存到本机，不上传；包含密钥，请妥善保存。',target:p['备份']??'',categories:Array.isArray(p.categories)?p.categories.map(x=>categoryLabels[x]??x).join('、'):'',confirm:p.action==='restore'?'确认恢复':'确认备份'};
 if(pending.tool==='langbai_library')return {title:p.action==='delete'?'删除所选资料':'保存资料修改',description:'执行前创建可恢复备份。保留图片文件，不自动生成图片。',target:[categoryLabels[p.collection]??p.collection,p['名称']??p.id].filter(Boolean).join(' · '),confirm:p.action==='delete'?'确认删除':'确认保存'};
 if(pending.tool==='langbai_tasks')return {title:p.action==='resume'?'继续生成队列':'移除排队任务',description:p.action==='resume'?'继续执行尚未完成的排队任务，可能消耗 Anlas。':'仅移除待执行任务，已生成的图片保留。',target:p.id??'',confirm:p.action==='resume'?'确认继续':'确认移除'};
 return {title:pending.title??'确认软件操作',description:pending.kind==='operation'?'请检查本次操作内容。确认后执行一次，软件不再重复确认。':`当前会话请求 ${pending.count} 张图片处理任务，可能消耗 Anlas。`,target:'',confirm:pending.kind==='operation'?'确认执行':'确认生成'};
}
