export const descriptions={
 model:'选择负责生成图片的模型。不同模型支持的尺寸、采样器和功能可能不同；切换后请检查其他选项。',
 stylePrompt:'描述画风、媒介和画师倾向。这里编辑工作台参数；上方选择的会话风格只作用于当前酒馆会话。',
 positivePrompt:'描述希望出现的人物、动作、构图和场景。保存只修改参数，不会立即生成图片。',
 negativePrompt:'描述希望减少或避免出现的内容和画面缺陷。它不是绝对禁止清单，效果取决于模型。',
 width:'输出图片的横向像素数。宽高共同决定像素总量，可能影响生成耗时及费用；仍需符合模型限制。',
 height:'输出图片的纵向像素数。宽高比例会影响构图；仍需符合模型允许的尺寸与像素总量。',
 steps:'采样迭代次数。增加通常会延长生成时间，并不保证画质持续提升。',
 cfgScale:'提示词引导强度。较高时通常更强调提示词，过高可能出现生硬、过饱和等现象。',
 cfgRescale:'修正较强 CFG 引导造成的画面偏差。具体效果和支持情况取决于模型；0 表示不启用此修正。',
 sampler:'选择从噪声逐步生成图像的采样算法。不同算法的表现不同，没有对所有画面都最好的选项。',
 noiseSchedule:'设置采样过程中噪声变化的计划。是否生效取决于所选模型和采样器。',
 seed:'控制初始随机噪声。相同种子配合相同模型及其他参数，有助于比较改动；种子模式仍会影响实际使用值。',
 seedMode:'决定每张图片使用随机种子、固定种子或按顺序变化的种子。比较参数时可选择固定种子。',
 ucPreset:'选择模型提供的负面提示预设。不同模型支持的预设可能不同。',
 qualityPreset:'选择质量相关的预设组合；实际使用内容取决于当前模型和软件配置。',
 qualityToggle:'启用模型提供的质量提示词。可与手写提示词共同影响结果。',
 transparentBackground:'请求透明背景；仅在支持此功能的模型或工具中生效。',
 smea:'启用 SMEA 采样增强；只在支持该功能的模型与采样器中生效。',
 smeaDyn:'启用动态 SMEA；依赖所选模型与采样器的支持。',
 variety:'调整模型支持的多样性选项，可能改变输出变化程度。',
 fileNamePrefix:'保存生成图片时使用的文件名前缀，不会改变图像内容。',
 batchCount:'一次批量任务计划生成的张数。酒馆自动生成还受当前会话授权额度限制。',
 batchIntervalSeconds:'批量任务中两次生成之间的等待时间，单位为秒。',
 inpaintModel:'选择处理局部重绘的模型；需与原图及所用功能兼容。',
 inpaintStrength:'局部重绘对选中区域的改动程度。数值较高通常更容易偏离原图。',
 inpaintNoise:'局部重绘时加入的噪声程度，影响细节变化。',
 inpaintPositivePrompt:'描述希望在局部重绘区域出现的内容。',
 brushSize:'局部重绘蒙版笔刷的大小；不会直接改变生成图片尺寸。',
 brushOpacity:'绘制蒙版时笔刷的不透明程度。',
 brushShape:'绘制局部重绘蒙版时使用的笔刷形状。',
 upscaleScale:'超分辨率放大的倍率。MAX 按当前工具允许的上限处理。',
 directorTool:'选择上色、线稿、表情或背景处理等导演工具；不同工具需要不同参数。',
 strength:'图生图对输入图片的改动程度。数值越大，结果通常越容易偏离原图。',
 noise:'图生图加入的噪声程度，影响生成结果与原图的相似程度。',
 extraNoiseSeed:'控制额外噪声的随机来源，用于比较图生图的细节变化。',
 defry:'调整增强工具的处理强度，实际效果取决于选中的工具。',
 colorizePrompt:'为上色工具描述希望使用的颜色或上色方向。',
 emotion:'表情工具希望生成的情绪或表情类型。',
 emotionLevel:'表情调整的强弱程度。',
 language:'切换软件界面的显示语言，不会翻译已保存的提示词或对话。',
 theme:'选择浅色、深色或跟随系统的界面外观。',
 reduceMotion:'减少界面切换及反馈动画，不改变生成结果。',
 autoComplete:'输入提示词时显示补全建议。',
 weightHighlight:'在编辑器中突出显示提示词权重，便于检查写法。',
 promptRandomizer:'启用软件支持的提示词随机化功能。',
 superDrop:'启用增强拖放交互，方便把文件或图片带入工作台。',
 streamPreviewEnabled:'生成时显示支持的过程预览；不代表图片已完成保存。',
 showFloatingToolbar:'显示工作台悬浮操作工具栏。',
 historyJumpAfterGenerate:'生成完成后是否自动转到历史记录。',
 loggingEnabled:'记录软件运行日志，用于排查问题。',
 keepImageMetadata:'在保存的图片中保留生成参数；分享图片前请留意其中可能含有提示词。',
 saveToGallery:'在支持的设备上把生成图片保存到系统相册。',
 autoBackupEnabled:'启用定期自动备份，具体包含内容由备份选项决定。',
 autoBackupIntervalHours:'两次自动备份之间的间隔，单位为小时。',
 autoBackupRetentionCount:'自动备份保留的历史份数；清理行为按软件备份规则执行。',
 autoBackupIncludeImages:'自动备份是否包含图片文件。开启后备份可能明显增大。',
 lockStylePrompt:'锁定工作台使用的风格提示词；请同时检查已锁定的风格内容。',
 lockNegativePrompt:'锁定工作台使用的负面提示词；请同时检查已锁定的负面内容。',
 savedStylePrompt:'风格锁定启用时使用的已保存提示词。',
 savedNegativePrompt:'负面提示词锁定启用时使用的已保存内容。',
 persistGenerateParams:'重新启动软件后恢复常规生图参数。',persistI2IParams:'重新启动软件后恢复图生图参数。',
 persistInpaintParams:'重新启动软件后恢复局部重绘参数。',persistUpscaleParams:'重新启动软件后恢复超分参数。',persistDirectorParams:'重新启动软件后恢复导演工具参数。',
 visionApiModel:'图片识别和反推请求使用的模型名称；必须是所配置服务支持的模型。',
 visionSystemPrompt:'图片反推时提供给模型的系统指令。',convertApiModel:'提示词转换请求使用的模型名称。',convertSystemPrompt:'提示词转换时提供给模型的系统指令。',
 agentApiModel:'酒馆对话请求使用的模型名称；应与当前服务商提供的模型标识一致。',agentProviderName:'酒馆模型服务商的显示名称，用于识别当前配置。',
 agentContextWindow:'对话模型可使用的上下文窗口大小，按 Token 计；请按实际模型能力设置。',
 agentMaxOutputTokens:'单次模型回复允许输出的最大 Token 数；不应超过上下文窗口或服务商限制。',
 agentAutoCompact:'上下文较长时自动压缩已有内容；摘要可能损失部分细节。',agentVisionEnabled:'声明酒馆模型是否支持识别图片，开启前需确认模型支持。',
 reversePromptMode:'选择反推结果采用的提示词形式。',convertMode:'选择提示词转换的处理方式。',
 reversePromptTemplateVersion:'选择图片反推使用的提示词模板版本。',convertPromptTemplateVersion:'选择提示词转换使用的模板版本。',
 reverseConvertDshEnabled:'让反推与转换流程使用配置的酒馆处理能力。',reverseConvertDshMode:'选择酒馆参与反推或转换时采用的模式。',
 comicAnalyzePromptTemplate:'分析漫画内容时使用的提示词模板。',translateProvider:'选择翻译请求使用的服务。',translateAiModel:'选择 AI 翻译使用的模型名称。',
 stylePromptPresetSort:'决定风格预设在列表中的排列顺序。',historyRetentionDays:'图片历史记录的保留期限，单位为天；请留意软件的清理规则。',aitagCacheRetentionDays:'反推标签缓存的保留期限，单位为天。',
};
export function parameterHelp(key,rule={}){
 const lines=[descriptions[key]??'此选项由当前工作台提供。修改前请核对当前模型是否支持；保存不会立即生成图片。'];
 if(rule.type==='number')lines.push(`允许范围：${rule.min??'未限定'}～${rule.max??'未限定'}${rule.step?`；步长：${rule.step}`:''}。`);
 if(rule.enum)lines.push(`请从下拉列表中的 ${rule.enum.length} 个有效选项选择。`);
 lines.push(rule.persistence==='session'?'只对当前会话生效，重启后不保留。':'普通参数保存后直接生效，不会触发生图。需要确认的操作会在 Agent 内提示。');
 return lines.join('\n');
}
