import React,{useEffect,useState} from 'react';
import {startPolling} from './client-state.js';
import {ParameterHelp,helpCSS} from './parameter-help-ui.js';
const h=React.createElement;
export const groups={params:'常规生图',workbench:'批量 / 重绘 / 后期',i2iParams:'图生图',augmentOptions:'增强与导演工具',settings:'软件设置'};
export const labels={model:'生成模型',stylePrompt:'风格提示词',positivePrompt:'正面提示词',negativePrompt:'负面提示词',width:'图片宽度',height:'图片高度',steps:'采样步数',cfgScale:'提示词引导 CFG',cfgRescale:'CFG 引导修正',sampler:'采样器',noiseSchedule:'噪声计划',seed:'随机种子',seedMode:'种子模式',ucPreset:'负面预设',qualityPreset:'质量预设',qualityToggle:'质量提示词',transparentBackground:'透明背景',smea:'SMEA',smeaDyn:'动态 SMEA',variety:'多样性',fileNamePrefix:'文件名前缀',batchCount:'批量张数',batchIntervalSeconds:'批次间隔（秒）',inpaintModel:'局部重绘模型',inpaintStrength:'局部重绘幅度',inpaintNoise:'局部重绘噪声',inpaintPositivePrompt:'局部重绘提示词',brushSize:'笔刷大小',brushOpacity:'笔刷不透明度',brushShape:'笔刷形状',upscaleScale:'超分倍率',directorTool:'导演工具',strength:'重绘幅度',noise:'噪声强度',extraNoiseSeed:'额外噪声种子',defry:'增强强度',colorizePrompt:'上色提示词',emotion:'表情类型',emotionLevel:'表情强度',language:'界面语言',theme:'主题',reduceMotion:'减少动画',autoComplete:'提示词补全',weightHighlight:'权重高亮',promptRandomizer:'提示词随机化',superDrop:'增强拖放',streamPreviewEnabled:'流式预览',showFloatingToolbar:'悬浮工具栏',historyJumpAfterGenerate:'生成后跳转历史',loggingEnabled:'记录日志',keepImageMetadata:'保留图片参数',saveToGallery:'保存到系统相册',autoBackupEnabled:'自动备份',autoBackupIntervalHours:'备份间隔（小时）',autoBackupRetentionCount:'保留备份数量',autoBackupIncludeImages:'备份包含图片',lockStylePrompt:'锁定风格提示词',lockNegativePrompt:'锁定负面提示词',savedStylePrompt:'已锁定的风格提示词',savedNegativePrompt:'已锁定的负面提示词',persistGenerateParams:'记住生图参数',persistI2IParams:'记住图生图参数',persistInpaintParams:'记住重绘参数',persistUpscaleParams:'记住超分参数',persistDirectorParams:'记住导演参数',visionApiModel:'图像识别模型',visionSystemPrompt:'反推系统提示词',convertApiModel:'提示词转换模型',convertSystemPrompt:'转换系统提示词',agentApiModel:'酒馆对话模型',agentProviderName:'酒馆服务商名称',agentContextWindow:'酒馆上下文窗口',agentMaxOutputTokens:'酒馆最大输出 Token',agentAutoCompact:'自动压缩上下文',agentVisionEnabled:'酒馆视觉能力',reversePromptMode:'反推提示词模式',convertMode:'转换提示词模式',reversePromptTemplateVersion:'反推模板版本',convertPromptTemplateVersion:'转换模板版本',reverseConvertDshEnabled:'启用酒馆提示词处理',reverseConvertDshMode:'酒馆处理模式',comicAnalyzePromptTemplate:'漫画分析模板',translateProvider:'翻译服务',translateAiModel:'翻译模型',stylePromptPresetSort:'风格排列顺序',historyRetentionDays:'图片历史保留天数',aitagCacheRetentionDays:'反推缓存保留天数'};
const hints={width:'按指定步长调整；模型与像素总量限制仍会检查。',height:'按指定步长调整；模型与像素总量限制仍会检查。',seed:'固定种子时便于复现；随机模式会在生成时选择新种子。',cfgScale:'控制提示词对图像的引导强度。',strength:'数值越大，重绘对原图的改动通常越明显。',agentMaxOutputTokens:'不应大于上下文窗口。',model:'切换模型后，部分不兼容参数可能需要重新选择。',noiseSchedule:'是否实际生效取决于所选模型。',savedStylePrompt:'修改前请检查风格锁定状态。',savedNegativePrompt:'修改前请检查负面提示词锁定状态。'};
export function fieldValue(snapshot,target,key){return (target==='settings'?snapshot.settings:target==='workbench'?snapshot.generation:snapshot.generation?.[target])?.[key];}
export function parseValue(rule,value){
 if(rule.enum){const found=rule.enum.find(x=>String(x)===String(value));if(found===undefined)throw Error('请选择有效选项');return found;}
 if(rule.type==='boolean')return value===true||value==='true';
 if(rule.type==='number'){if(String(value).trim()==='')throw Error('请输入数值');const n=Number(value);if(!Number.isFinite(n)||n<(rule.min??-Infinity)||n>(rule.max??Infinity)||(rule.step&&Math.abs(n/rule.step-Math.round(n/rule.step))>1e-8))throw Error('数值超出范围或步长');return n;}
 return String(value);
}
export const optionLabels={'nai-diffusion-5-full':'NAI 5 完整版','nai-diffusion-5-curated':'NAI 5 精选版','random':'随机','fixed':'固定','increment':'递增','decrement':'递减','light':'浅色','dark':'深色','system':'跟随系统','circle':'圆形','square':'方形','mixed':'混合提示词','natural':'自然语言','tags':'纯标签','bg-removal':'移除背景','lineart':'线稿','sketch':'草图','colorize':'上色','emotion':'表情','declutter':'清理画面','native':'原生调度','karras':'Karras 调度','exponential':'指数调度','polyexponential':'多项指数调度','k_euler':'Euler','k_euler_ancestral':'Euler 祖先采样','k_dpmpp_2m':'DPM++ 2M','k_dpmpp_2s_ancestral':'DPM++ 2S 祖先采样','k_dpmpp_sde':'DPM++ SDE','ddim_v3':'DDIM v3','nai-diffusion-4-5-full':'NAI 4.5 完整版','nai-diffusion-4-5-curated':'NAI 4.5 精选版','nai-diffusion-4-full':'NAI 4 完整版','nai-diffusion-4-curated-preview':'NAI 4 精选预览版','nai-diffusion-3':'NAI 3','nai-diffusion-furry-3':'NAI Furry 3','zh-CN':'简体中文','zh-TW':'繁體中文','en-US':'English','ja-JP':'日本語','ko-KR':'한국어'};
const shown=v=>typeof v==='boolean'?(v?'开启':'关闭'):v==null?'—':typeof v==='object'?JSON.stringify(v):optionLabels[v]??String(v);
export function ParameterPanel({call}){
 useEffect(()=>{const style=document.createElement('style');style.textContent=helpCSS;document.head.append(style);return()=>style.remove()},[]);
 const [snapshot,setSnapshot]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [group,setGroup]=useState('params'),[query,setQuery]=useState(''),[edit,setEdit]=useState(null);
 const read=async()=>{const next=await call('langbai_read_studio_state');if(!next?.writableSchema)throw Error('软件连接没有返回参数结构，请从软件内重新启动 Agent');setSnapshot(next);return next;};
 useEffect(()=>{let live=true;call('langbai_read_studio_state').then(v=>{if(live){if(!v?.writableSchema)throw Error('软件连接没有返回参数结构，请从软件内重新启动 Agent');setSnapshot(v);}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false};},[call]);
 useEffect(()=>{if(edit||busy)return;return startPolling({read:()=>call('langbai_read_studio_state'),publish:setSnapshot,onError:e=>setError(e.message),isVisible:()=>document.visibilityState==='visible'});},[call,edit,busy]);
 async function run(fn){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const save=()=>run(async()=>{const rule=snapshot.writableSchema[edit.target][edit.key];const result=await call('langbai_update_studio_config',{expectedRevision:edit.revision,target:edit.target,patch:{[edit.key]:parseValue(rule,edit.value)}});setEdit(null);await read();setMessage(result?.scope==='current-session'?'已应用到当前会话并回读（重启后不保留）':'已保存并回读软件当前值');});
 const search=query.trim().toLowerCase();
 return h('section',{className:'studio-library studio-parameters','aria-busy':busy},
  h('div',{className:'studio-library-toolbar'},h('div',null,h('strong',null,'软件实时参数'),h('small',{className:'studio-library-muted'},snapshot?`${'工作台实时参数（不含设置窗口未保存草稿）'} · ${new Date(snapshot.capturedAt).toLocaleTimeString()}`:'正在连接本机软件…')),h('button',{disabled:busy||!!edit,onClick:()=>run(read)},'刷新')),
  h('p',{className:'studio-library-muted'},'参数按类别展示。普通参数保存后直接生效；不会触发生成。未开放的选项请在软件设置中修改。'),
  error?h('div',{role:'alert',className:'studio-library-error'},error,h('button',{disabled:busy,onClick:()=>run(async()=>{await read();setEdit(null);})},'刷新并取消当前编辑')):null,
  message?h('p',{role:'status'},message):null,
  h('input',{'aria-label':'搜索参数',placeholder:'搜索名称或字段，例如：种子 / CFG / 模型',value:query,onChange:e=>setQuery(e.target.value)}),
  h('nav',{className:'studio-parameter-tabs','aria-label':'参数类别'},...Object.keys(snapshot?.writableSchema??groups).map(k=>h('button',{key:k,'aria-pressed':k===group,onClick:()=>setGroup(k)},groups[k]??k))),
  ...Object.entries(snapshot?.writableSchema??{}).filter(([k])=>search||k===group).map(([target,rules])=>h('section',{key:target},search?h('h3',null,groups[target]??target):null,
   h('div',{className:'studio-parameter-fields'},...Object.entries(rules).filter(([key])=>!(target==='params'&&key==='positivePrompt')).filter(([key])=>!search||`${labels[key]??''} ${key}`.toLowerCase().includes(search)).map(([key,rule])=>{
    const active=edit?.target===target&&edit.key===key,value=fieldValue(snapshot,target,key),options=rule.enum??(rule.type==='boolean'?[true,false]:null);
    const control=options?h('select',{'aria-label':labels[key]??key,value:String(active?edit.value:value),disabled:busy||!!edit&&!active,onChange:e=>setEdit({target,key,revision:edit?.revision??snapshot.revision,value:e.target.value})},...options.map(v=>h('option',{key:String(v),value:String(v)},key==='upscaleScale'&&(v===0||v==='max')?'MAX':shown(v)))):h(rule.type==='string'?'textarea':'input',{'aria-label':labels[key]??key,type:rule.type==='number'?'number':undefined,rows:3,value:(active?edit.value:value)??'',min:rule.min,max:rule.type==='number'?rule.max:undefined,step:rule.step??'any',disabled:busy||!!edit&&!active,onChange:e=>setEdit({target,key,revision:edit?.revision??snapshot.revision,value:e.target.value})});
    return h('article',{key,className:'studio-parameter-card'},h('div',{className:'studio-library-toolbar'},h('strong',null,labels[key]??key),h(ParameterHelp,{name:labels[key]??key,field:key,rule})),
     rule.type==='number'?h('small',null,`范围 ${rule.min??'不限'}–${rule.max??'不限'}${rule.step?` · 步长 ${rule.step}`:''}`):null,
     rule.persistence==='session'?h('small',null,'仅当前会话 · 重启后不保留'):null,
     hints[key]?h('p',{className:'studio-library-muted'},hints[key]):null,
     control,
     h('div',{className:'studio-parameter-actions'},active?h(React.Fragment,null,h('button',{disabled:busy,onClick:()=>setEdit(null)},'取消'),h('button',{disabled:busy,onClick:save},busy?'保存中…':'保存此项')):null));
   })))));
}
