import React,{useEffect,useState,useRef} from 'react';
const h=React.createElement;
export function TemplatePanel({call}) {
 const fileInput=useRef(null);
 const [kind,setKind]=useState('convert'),[mode,setMode]=useState(null),[version,setVersion]=useState(null);
 const [snapshot,setSnapshot]=useState(null),[body,setBody]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let live=true;setSnapshot(null);setError('');call('studio_prompt_template',{kind,...(mode?{mode}:{}),...(version?{templateVersion:version}:{})}).then(s=>{if(live){setSnapshot(s);setBody(s.body)}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[call,kind,mode,version]);
 const save=async(reset=false)=>{setBusy(true);setError('');try{const s=await call('studio_save_prompt_template',{kind:snapshot.kind,mode:snapshot.mode,templateVersion:snapshot.templateVersion,expectedRevision:snapshot.revision,body:reset?'':body,restoreDefault:reset});setSnapshot(s);setBody(s.body);setMessage('已保存到软件共用模板；下一次提示词请求生效，未生成图片。')}catch(e){setError(e.message)}finally{setBusy(false)}};
 async function importFile(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;setError('');try{if(file.size>240000)throw Error('模板文件过大');let value=await file.text();if(file.name.toLowerCase().endsWith('.json')){const json=JSON.parse(value);value=typeof json==='string'?json:json.body??json[snapshot.mode];}if(typeof value!=='string'||!value.trim()||value.length>60000)throw Error('请导入 TXT 文本或包含 body / 当前模式字段的 JSON');setBody(value);setMessage('已载入草稿；检查后点击保存，不会自动覆盖模板。')}catch(e){setError(e.message)}}
 return h('section',{className:'studio-library'},h('h3',null,'软件共用提示词模板'),h('p',{className:'studio-library-muted'},'文字描述使用转换模板，参考图使用反推模板。默认混合模式；导入和编辑保存到软件同一套模板，风格与负面提示词不变。'),
 h('div',{className:'studio-library-toolbar'},h('label',null,'用途 ',h('select',{value:kind,disabled:busy,onChange:e=>{setKind(e.target.value);setVersion(null);setMessage('')}},h('option',{value:'convert'},'文字转换'),h('option',{value:'reverse'},'图片反推'))),h('label',null,'模式 ',h('select',{value:mode??snapshot?.mode??'mixed',disabled:busy,onChange:e=>{setMode(e.target.value);setMessage('')}},h('option',{value:'mixed'},'混合模式'),h('option',{value:'tags'},'标签'),h('option',{value:'natural'},'自然语言'))),h('label',null,'版本 ',h('select',{value:version??snapshot?.templateVersion??'v5',disabled:busy,onChange:e=>{setVersion(e.target.value);setMessage('')}},h('option',{value:'v5'},'V5'),h('option',{value:'v4.5'},'V4.5')))),
 snapshot?h(React.Fragment,null,h('p',null,snapshot.source==='custom'?'当前内容：软件自定义模板':'当前内容：软件内置模板'),h('textarea',{'aria-label':'共用模板内容',rows:12,value:body,disabled:busy,onChange:e=>setBody(e.target.value),style:{width:'100%',boxSizing:'border-box'}}),h('div',{className:'studio-library-toolbar'},h('input',{ref:fileInput,type:'file',accept:'.txt,.json',hidden:true,disabled:busy,onChange:importFile}),h('button',{disabled:busy,onClick:()=>fileInput.current?.click()},'导入模板文件'),h('button',{disabled:busy,onClick:()=>save()},'保存模板与选择'),h('button',{disabled:busy,onClick:()=>save(true)},'恢复当前模式默认模板'))):h('p',null,error?'模板读取未完成':'读取本机软件模板…'),error?h('p',{role:'alert'},error):null,message?h('p',{role:'status'},message):null);
}
