import {describe,it,expect,vi} from 'vitest';
import {createApiTools,type ApiAdapter} from './agent-api-tools';
import {validateApiRequest} from '../../src/agent/api-contract';
function fixture(){let state={config:{baseUrl:'https://api.example.com/v1',model:'model-a'},secret:'local-test-secret'};const adapter:ApiAdapter={profiles:()=>['convert'],read:async()=>structuredClone(state),write:async(_p,next,expected)=>{if(JSON.stringify(state)!==JSON.stringify(expected))throw Error('changed');state=structuredClone(next);},test:vi.fn(async()=>({status:200,models:['model-a']}))};const approve=vi.fn(async()=>true);return {adapter,approve,service:createApiTools(adapter,approve),state:()=>state};}
describe('local API workflow',()=>{
 it('read hides key; confirmed configure persists, tests saved endpoint; no arbitrary test URL',async()=>{const {service,approve,adapter,state}=fixture();const call=(args:Record<string,unknown>)=>service.execute({tool:'langbai_api',sessionId:'one',args});let r=await call({action:'read',profile:'convert'});expect(r.ok,r.output).toBe(true);expect(r.output).not.toContain('local-test-secret');r=await call({action:'configure',profile:'convert',expectedRevision:(r.data as any).revision,patch:{model:'model-b'}});expect(r.ok,r.output).toBe(true);expect(state().config.model).toBe('model-b');expect(approve).toHaveBeenCalledTimes(1);expect((await call({action:'test',profile:'convert'})).ok).toBe(true);expect(adapter.test).toHaveBeenCalledTimes(1);expect((await call({action:'test',profile:'convert',url:'https://other.example'})).ok).toBe(false);});
 it('credential UI is session-bound and one-shot; never returns submitted secret',async()=>{const {service,state}=fixture();const call=(tool:string,args:Record<string,unknown>,sessionId='one')=>service.execute({tool,sessionId,args});const r=await call('langbai_api',{action:'read',profile:'convert'});expect((await call('langbai_api',{action:'credential',profile:'convert',expectedRevision:(r.data as any).revision})).ok).toBe(true);const pending=await call('studio_api_input',{});expect(pending.output).not.toContain('local-test-secret');expect((await call('studio_resolve_api_input',{id:(pending.data as any).id,value:'replacement'},'two')).ok).toBe(false);const done=await call('studio_resolve_api_input',{id:(pending.data as any).id,value:'replacement'});expect(done.ok,done.output).toBe(true);expect(done.output).not.toContain('replacement');expect(state().secret).toBe('replacement');expect((await call('studio_resolve_api_input',{id:(pending.data as any).id,value:'again'})).ok).toBe(false);});
 it('refuses injected secret, stale revision, credentials in URL, redirect and unknown action',async()=>{for(const args of [{action:'test',profile:'convert',secret:'bad'},{action:'configure',profile:'convert',expectedRevision:'x',patch:{baseUrl:'https://u:p@example.com'}},{action:'unknown',profile:'convert'}])expect(()=>validateApiRequest(args)).toThrow();const {service}=fixture();expect((await service.execute({tool:'langbai_api',sessionId:'one',args:{action:'configure',profile:'convert',expectedRevision:'stale',patch:{model:'b'}}})).ok).toBe(false);});
 it('cancel and revision drift leave data unchanged; errors never echo private provider data',async()=>{const f=fixture();f.approve.mockImplementation(async()=>false);const read=await f.service.execute({tool:'langbai_api',sessionId:'one',args:{action:'read',profile:'convert'}});const r=await f.service.execute({tool:'langbai_api',sessionId:'one',args:{action:'clearCredential',profile:'convert',expectedRevision:(read.data as any).revision}});expect(r.ok).toBe(false);expect(f.state().secret).toBe('local-test-secret');f.adapter.test=async()=>{throw Error('Authorization local-test-secret')};const tested=await f.service.execute({tool:'langbai_api',sessionId:'one',args:{action:'test',profile:'convert'}});expect(tested.output).not.toContain('local-test-secret');});
});
