import type { ArtistStyleCatalogScope } from "../../src/types";

type VisualScope = Exclude<ArtistStyleCatalogScope, "all" | "copyright">;

const QUALITY = new Set([
  "highres",
  "absurdres",
  "absurdly_detailed_composition",
  "official_art",
  "official_style",
]);

const RENDER_3D = new Set([
  "3d",
  "8-bit",
  "ambient_occlusion",
  "cel_rendering",
  "game_cg",
  "global_illumination",
  "low_poly",
  "minecraft_(style)",
  "pc-98_(style)",
  "photorealistic",
  "physically_based_rendering",
  "pixel_art",
  "pixelated",
  "pokemon_rgby_(style)",
  "ray_tracing",
  "realistic",
  "subsurface_scattering",
  "toon_(style)",
  "visual_novel_cg",
  "voxel_art",
  "wireframe",
]);

const MEDIUM = new Set([
  "8-bit",
  "anime_coloring",
  "airbrush_(medium)",
  "ben-day_dots",
  "black_outline",
  "brush_stroke",
  "cel_rendering",
  "chalk_drawing",
  "charcoal_drawing",
  "child's_drawing",
  "collage",
  "colored_lineart",
  "colored_pencil",
  "color_trace",
  "comic",
  "crayon_drawing",
  "crosshatching",
  "digital_painting",
  "engraving",
  "faux_traditional_media",
  "full_page_comic",
  "game_cg",
  "gouache",
  "grey_outline",
  "halftone",
  "hatching",
  "hatching_(texture)",
  "impasto",
  "ink_wash_painting",
  "illustration",
  "ligne_claire",
  "linear_hatching",
  "linocut",
  "lineart",
  "lithograph",
  "marker_(medium)",
  "mixed_media",
  "no_lineart",
  "official_art",
  "official_style",
  "oil_painting",
  "outline",
  "painterly",
  "pastel_(medium)",
  "pixel_art",
  "pointillism",
  "screenprint",
  "scribble",
  "segmented_comic",
  "silent_comic",
  "sketch",
  "sumi-e",
  "tegaki",
  "thick_lineart",
  "thick_outlines",
  "traditional_media",
  "vertical_comic",
  "visual_novel_cg",
  "watercolor",
  "watercolor_effect",
  "western_comics_(style)",
  "woodcut",
  "woven_hatching",
]);

const LIGHTING = new Set([
  "ambient_lighting",
  "backlighting",
  "blue_light",
  "candlelight",
  "chiaroscuro",
  "cinematic_lighting",
  "dappled_moonlight",
  "dappled_sunlight",
  "diffused_lighting",
  "dim_lighting",
  "dramatic_lighting",
  "flat_lighting",
  "golden_hour",
  "hard_lighting",
  "high-key_lighting",
  "light",
  "low-key_lighting",
  "moonlight",
  "natural_lighting",
  "neon_lighting",
  "orange_light",
  "overlighting",
  "red_light",
  "rim_lighting",
  "screen_light",
  "shadow",
  "sidelighting",
  "soft_lighting",
  "studio_lighting",
  "sunlight",
  "underlighting",
  "volumetric_lighting",
  "window_light",
  "yellow_light",
]);

const COLOR = new Set([
  "analogous_colors",
  "black_and_white",
  "color-coded",
  "color_contrast",
  "color_coordination",
  "color_grading",
  "complementary_colors",
  "cool_colored",
  "cool_colors",
  "duotone",
  "flat_color",
  "grayscale",
  "hue_shifting",
  "imageboard_colors",
  "inverted_colors",
  "iridescent_colors",
  "limited_palette",
  "monochrome",
  "multiple_theme_colors",
  "muted_color",
  "muted_colors",
  "neapolitan_palette",
  "negative",
  "neon_palette",
  "pale_color",
  "pale_colors",
  "palette_swap",
  "partially_colored",
  "pastel_colors",
  "pastels",
  "reverse_palettes",
  "sepia",
  "spot_color",
  "vibrant_colors",
  "warm_colored",
  "warm_colors",
]);

const TEXTURE = new Set([
  "ben-day_dots",
  "brush_stroke",
  "canvas_texture",
  "crosshatching",
  "film_grain",
  "glossy",
  "grain",
  "halftone",
  "hatching_(texture)",
  "impasto",
  "iridescent",
  "linear_hatching",
  "matte",
  "metallic",
  "paper_texture",
  "rough_texture",
  "semi-transparent",
  "smooth_texture",
  "stipple",
  "stippling",
  "texture",
  "translucent",
  "transparent",
  "woven_hatching",
]);

const STYLIZATION = new Set([
  "abstract",
  "animification",
  "anime_coloring",
  "art_deco",
  "art_nouveau",
  "art_shift",
  "baroque",
  "biopunk",
  "cartoonized",
  "chibi",
  "comic",
  "cubism",
  "cyber_sigilism",
  "egyptian_art",
  "expressionism",
  "fauvism",
  "faux_retro_artstyle",
  "faux_traditional_media",
  "flat_color",
  "impressionism",
  "maximalism",
  "minimalism",
  "multiple_style_parody",
  "official_style",
  "painterly",
  "partially_colored",
  "pixel_art",
  "pop_art",
  "realistic",
  "retrofuturism",
  "retro_artstyle",
  "rococo",
  "semi-realistic",
  "still_life",
  "style_parody",
  "stylized",
  "surreal",
  "surrealism",
  "symbolism",
  "weirdcore",
]);

const SCOPE_SETS: Record<Exclude<VisualScope, "style">, Set<string>> = {
  quality: QUALITY,
  render3d: RENDER_3D,
  medium: MEDIUM,
  lighting: LIGHTING,
  color: COLOR,
  texture: TEXTURE,
  stylization: STYLIZATION,
};

export function artistStyleExactNames(scope: ArtistStyleCatalogScope): string[] {
  if (scope === "copyright" || scope === "style") return [];
  if (scope === "all") {
    return [...new Set(Object.values(SCOPE_SETS).flatMap((set) => [...set]))];
  }
  return [...SCOPE_SETS[scope]];
}

export function isExplicitDanbooruStyleTag(name: string): boolean {
  return name.toLocaleLowerCase().endsWith("_(style)");
}

export function matchesArtistStyleScope(
  rawName: string,
  category: number,
  scope: ArtistStyleCatalogScope,
): boolean {
  const name = rawName.trim().toLocaleLowerCase();
  if (!name) return false;
  if (scope === "copyright") return category === 3;
  if (scope === "all" && category === 3) return true;
  if (category !== 0) return false;
  if (scope === "style") return isExplicitDanbooruStyleTag(name);
  if (scope === "all") {
    return isExplicitDanbooruStyleTag(name) || Object.values(SCOPE_SETS).some((set) => set.has(name));
  }
  return SCOPE_SETS[scope].has(name) || (scope === "stylization" && isExplicitDanbooruStyleTag(name));
}
