import {it,expect} from 'vitest';
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {HarnessEngine} from './harness-engine';
it('loads managed responsive UI outside user plugins and retains earlier versions and user files',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'studio-responsive-'));
 const source=path.join(root,'app-ui'),home=path.join(root,'engine');await fs.mkdir(path.join(source,'lib'),{recursive:true});
 for(const [name,text] of Object.entries({'package.json':'{"name":"@langbai/dsh-studio-responsive"}','index.js':'export function apply() {}','lib/client.js':'version one'}))await fs.writeFile(path.join(source,name),text);
 const user=path.join(home,'user-home/profiles/node_modules/user-plugin');await fs.mkdir(user,{recursive:true});await fs.writeFile(path.join(user,'custom.txt'),'user-owned');
 const engine=new HarnessEngine({root:home,seed:root,workspace:root,responsiveSource:source,openBrowser:async()=>{},bridge:async()=>({env:{},close:async()=>{}})});
 const first=await (engine as any).presentationPatch(root) as string;
 expect(first.startsWith(path.join(home,'presentation'))).toBe(true);
 expect(await fs.readFile(first,'utf8')).toContain('/index.js');
 expect(await (engine as any).presentationPatch(root)).toBe(first);
 await fs.writeFile(path.join(source,'lib/client.js'),'version two');
 const second=await (engine as any).presentationPatch(root) as string;expect(second).not.toBe(first);
 expect(await fs.readFile(path.join(path.dirname(first),'lib/client.js'),'utf8')).toBe('version one');
 expect(await fs.readFile(path.join(user,'custom.txt'),'utf8')).toBe('user-owned');
 expect(await fs.readdir(path.join(home,'user-home/profiles/node_modules'))).toEqual(['user-plugin']);
});
it('has a reproducible CSS bundle, scoped phone rules and a removable lifecycle',async()=>{
 const base=new URL('../../harness/plugins/studio-responsive/',import.meta.url);
 const css=await fs.readFile(new URL('responsive.css',base),'utf8');
 const install=(await fs.readFile(new URL('install.js',base),'utf8')).replace('export function','function');
 const expected=`// Generated by harness/build-responsive.mjs\nwindow.__ModuleLoader__.load({id:'@langbai/dsh-studio-responsive',factory(){\n${install}\nreturn {apply(ctx){ctx.effect(()=>installResponsive(${JSON.stringify(css)}));}};}});\n`;
 expect(await fs.readFile(new URL('lib/client.js',base),'utf8')).toBe(expected);
 expect(css).toContain('@media (max-width: 760px)');expect(css).not.toMatch(/user-scalable\s*=\s*no|zoom\s*:/);
 expect(install).toContain('observer.disconnect()');expect(install).toContain("composer:'InputBar'");
});
