import {it,expect,vi,afterEach} from 'vitest';
import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import crypto from 'node:crypto';import {gzipSync} from 'node:zlib';import {EventEmitter} from 'node:events';import {PassThrough} from 'node:stream';
const fixture=vi.hoisted(()=>({fail:false}));
vi.mock('./download-request',()=>({updateFetch:vi.fn()}));
vi.mock('node:child_process',()=>({spawn:vi.fn((_node,args,options)=>{
 const child=Object.assign(new EventEmitter(),{stdout:new PassThrough(),stderr:new PassThrough(),kill:vi.fn()});
 setTimeout(()=>{void (async()=>{
  if(fixture.fail){child.stderr.write('fixture installer failure');child.emit('close',1);return;}
  const dir=path.join(options.cwd,'node_modules/demo-plugin');await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'package.json'),JSON.stringify({name:'demo-plugin',version:'1.1.0'}));child.emit('close',0);
 })().catch(e=>child.emit('error',e));},0);return child;
})}));
import {spawn} from 'node:child_process';
import {updateFetch} from './download-request';
import {downloadPluginUpdates} from './harness-official-runtime';
import {verifyBundle} from './harness-policy';
const roots:string[]=[];const sha=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
function archive(){const name='package/bin/npm-cli.js',content='fixture npm';const h=Buffer.alloc(512);h.write(name);h.write('0000644\0',100);h.write('0000000\0',108);h.write('0000000\0',116);h.write(content.length.toString(8).padStart(11,'0')+'\0',124);h.fill(32,148,156);h.write('0',156);h.write('ustar\0',257);let sum=0;for(const n of h)sum+=n;h.write(sum.toString(8).padStart(6,'0')+'\0 ',148);return gzipSync(Buffer.concat([h,Buffer.from(content),Buffer.alloc(512-content.length),Buffer.alloc(1024)]));}
async function setup(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'plugin-download-test-'));roots.push(root);const dir=path.join(root,'versions/current');await fs.mkdir(path.join(dir,'runtime'),{recursive:true});const files={'node.exe':sha('installed node'),'runtime/bin.js':sha('installed runtime')};await fs.writeFile(path.join(dir,'node.exe'),'installed node');await fs.writeFile(path.join(dir,'runtime/bin.js'),'installed runtime');await fs.writeFile(path.join(dir,'manifest.json'),JSON.stringify({format:1,protocol:1,version:'0.1.7',upstream:'0.2.0-rc.2',platform:process.platform,arch:process.arch,node:'node.exe',cli:'runtime/bin.js',files}));const active=JSON.stringify({slot:'current'});await fs.writeFile(path.join(root,'active.json'),active);
 const bytes=archive(),installer={name:'npm',version:'10.9.4',dist:{tarball:'https://registry.npmjs.org/npm/-/npm-10.9.4.tgz',integrity:'sha512-'+crypto.createHash('sha512').update(bytes).digest('base64')}};
 vi.mocked(updateFetch).mockImplementation(async(url:any)=>String(url).endsWith('.tgz')?new Response(bytes):new Response(JSON.stringify(installer)));
 const changes=[{name:'demo-plugin',fromVersion:'1.0.0',version:'1.1.0',action:'upgrade',directory:'profiles/node_modules/demo-plugin',beforeHash:'a'.repeat(64),profiles:[{file:'studio.patch.yml',hash:'b'.repeat(64),index:0,kind:'row'}],canDisable:false,reason:'fixture',meta:{name:'demo-plugin',version:'1.1.0',peerDependencies:{'@deepseek-ai/dsh-tools':'^0.2.0-rc.1'},dist:{tarball:'https://registry.npmjs.org/demo-plugin/-/demo-plugin-1.1.0.tgz',integrity:'sha512-'+Buffer.alloc(64).toString('base64')}}}];
 return {root,active,changes:changes as any};
}
afterEach(async()=>{fixture.fail=false;vi.resetAllMocks();for(const r of roots.splice(0))if(path.dirname(r)===os.tmpdir()&&path.basename(r).startsWith('plugin-download-test-'))await fs.rm(r,{recursive:true,force:true});});
it('keeps runtime bytes, pins plugin dependencies, disables install scripts and uses the proxy registry',async()=>{const f=await setup();const result=await downloadPluginUpdates(f.root,f.changes,new AbortController().signal,()=>{});const m=JSON.parse(await fs.readFile(path.join(result,'manifest.json'),'utf8'));expect(m.upstream).toBe('0.2.0-rc.2');expect(await fs.readFile(path.join(result,'runtime/bin.js'),'utf8')).toBe('installed runtime');expect(await fs.readFile(path.join(f.root,'active.json'),'utf8')).toBe(f.active);await verifyBundle(result,m);const call=vi.mocked(spawn).mock.calls[0] as any;expect(call[1]).toContain('--ignore-scripts');expect(call[1].some((s:string)=>s.startsWith('--registry=http://127.0.0.1:'))).toBe(true);expect(JSON.parse(await fs.readFile(path.join(call[2].cwd,'package.json'),'utf8')).dependencies).toEqual({'demo-plugin':'1.1.0','@deepseek-ai/dsh-tools':'0.2.0-rc.2'});expect(vi.mocked(updateFetch).mock.calls.every(([u])=>!String(u).includes('dsh-0.2.0'))).toBe(true);});
it('installer failure never changes the active descriptor or runtime',async()=>{const f=await setup();fixture.fail=true;await expect(downloadPluginUpdates(f.root,f.changes,new AbortController().signal,()=>{})).rejects.toThrow('fixture installer failure');expect(await fs.readFile(path.join(f.root,'active.json'),'utf8')).toBe(f.active);expect(await fs.readFile(path.join(f.root,'versions/current/runtime/bin.js'),'utf8')).toBe('installed runtime');});
it('rejects cancellation and disables-only plans before publishing',async()=>{const f=await setup();await expect(downloadPluginUpdates(f.root,[{...f.changes[0],action:'disable'}],new AbortController().signal,()=>{})).rejects.toThrow('计划无效');const c=new AbortController();c.abort();await expect(downloadPluginUpdates(f.root,f.changes,c.signal,()=>{})).rejects.toThrow();expect(spawn).not.toHaveBeenCalled();expect(await fs.readFile(path.join(f.root,'active.json'),'utf8')).toBe(f.active);});
