import {it,expect,vi,afterEach} from 'vitest';
import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
vi.mock('./download-request',()=>({updateFetch:vi.fn()}));
import {updateFetch} from './download-request';
import {inventoryPluginReferences,parsePluginRows} from './harness-plugin-inventory';
import {planPluginUpgrades} from './harness-plugin-update';
import {disabledHarnessPlugin} from './harness-readiness';
import {HarnessEngine} from './harness-engine';
const roots:string[]=[];
afterEach(async()=>{vi.resetAllMocks();for(const r of roots.splice(0))if(path.dirname(r)===os.tmpdir()&&path.basename(r).startsWith('plugin-inventory-'))await fs.rm(r,{recursive:true,force:true});});
async function setup(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'plugin-inventory-'));roots.push(root);const write=async(name:string,data:unknown)=>{const file=path.join(root,'user-home',name);await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,typeof data==='string'?data:JSON.stringify(data));};return {root,write};}
it('includes ordinary configured plugins and bundles but ignores disabled rows and config strings',async()=>{const {root,write}=await setup();await write('profiles/web/package.json',{dsh:{profile:{bundles:['bundle-one']}}});await write('studio-community.patch.yml','- insert:\n    - id: mgr\n      name: dsh-plugin-mgr\n      config:\n        id: fake\n        name: not-a-plugin\n    - id: off\n      name: disabled-plugin\n      disabled: true\n');expect((await inventoryPluginReferences(root)).map(p=>p.name)).toEqual(['bundle-one','dsh-plugin-mgr']);await write('studio.patch.yml','- id: mgr\n  disabled: true\n');expect((await inventoryPluginReferences(root)).map(p=>p.name)).toEqual(['bundle-one']);});
it('parses !!js as inert data and excludes disabled groups',()=>{const result=parsePluginRows('- insert:\n    - id: good\n      name: good\n      config:\n        data: !!js process.exit(42)\n    - id: group\n      group: true\n      disabled: true\n      config:\n        - id: child\n          name: child\n');expect(result.map(p=>p.id)).toEqual(['good','group']);});
it('checks a normal plugin row against current Harness, including already compatible plugin updates',async()=>{const {root,write}=await setup();const pkg={name:'dsh-plugin-mgr',version:'0.2.10',peerDependencies:{'@deepseek-ai/dsh-tools':'^0.2.0-rc.1'}};await write('studio-community.patch.yml','- insert:\n    - id: studio-plugin-manager\n      name: dsh-plugin-mgr\n');await write('profiles/node_modules/dsh-plugin-mgr/package.json',pkg);const next={...pkg,version:'0.2.11',dist:{tarball:'https://registry.npmjs.org/dsh-plugin-mgr/-/dsh-plugin-mgr-0.2.11.tgz',integrity:'sha512-'+Buffer.alloc(64).toString('base64')}};vi.mocked(updateFetch).mockResolvedValue(new Response(JSON.stringify({versions:{'0.2.11':next}})));const plan=await planPluginUpgrades(root,'0.2.0-rc.2',new AbortController().signal,true);expect(plan).toHaveLength(1);expect(plan[0]).toMatchObject({version:'0.2.11',incompatible:false,canDisable:false,profiles:[{kind:'row',id:'studio-plugin-manager'}]});});
it('surfaces and deduplicates disabled-plugin diagnostics without calling the whole Agent stopped',()=>{const line='dsh: disabling profile plugin row "studio-plugin-manager": Plugin dsh-plugin-mgr@0.2.10 is incompatible with dsh 0.2.0-rc.2';expect(disabledHarnessPlugin(line)).toBe(line);expect(disabledHarnessPlugin('Agent ready')).toBeNull();const engine=new HarnessEngine({root:'unused',seed:'unused',workspace:'.',openBrowser:async()=>{},bridge:async()=>({env:{},close:async()=>{}})});engine.log(line);engine.log(line);expect(engine.snapshot().disabledPlugins).toHaveLength(1);expect(engine.snapshot().logs).toHaveLength(1);expect(engine.snapshot().logs[0].level).toBe('warn');});
it('does not upgrade children of a group disabled by a later patch',async()=>{const {root,write}=await setup();await write('profiles/web/cordis.patch.yml','- id: group\n  group: true\n  config:\n    - id: child\n      name: child-plugin\n');await write('studio.patch.yml','- id: group\n  disabled: true\n');expect(await inventoryPluginReferences(root)).toEqual([]);});
it('includes dependency pins for plugins enabled through rows rather than bundles',async()=>{const {root,write}=await setup();await write('profiles/web/package.json',{dependencies:{'dsh-plugin-mgr':'0.2.10'}});await write('studio.patch.yml','- insert:\n    - id: manager\n      name: dsh-plugin-mgr\n');expect((await inventoryPluginReferences(root)).map(r=>r.file)).toEqual(['studio.patch.yml','profiles/web/package.json']);});
