import {it,expect,vi,afterEach} from 'vitest';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {HarnessEngine} from './harness-engine';import {isNewerBundle} from './harness-policy';
const network=vi.hoisted(()=>vi.fn(async()=>{throw Error('Network must not be needed to identify an installation');}));vi.mock('./harness-update-check',()=>({checkHarnessUpdates:network}));const roots:string[]=[];
afterEach(async()=>{vi.clearAllMocks();for(const p of roots.splice(0))await fs.rm(p,{recursive:true,force:true});});
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'studio-installed-test-'));roots.push(root);const slot=path.join(root,'versions/current');await fs.mkdir(slot,{recursive:true});const manifest={format:1,protocol:1,version:'0.2.0',upstream:'0.1.7',platform:process.platform,arch:process.arch,node:'node.exe',cli:'runtime.js',files:{'node.exe':'a'.repeat(64),'runtime.js':'b'.repeat(64)}};await fs.writeFile(path.join(slot,'manifest.json'),JSON.stringify(manifest));await fs.writeFile(path.join(root,'active.json'),JSON.stringify({slot:'current'}));const make=()=>new HarnessEngine({root,seed:path.join(root,'seed'),workspace:root,openBrowser:async()=>{},bridge:async()=>({env:{},close:async()=>{}})});return{root,make};}
it('cold start identifies the installed version without querying or downloading',async()=>{const {make}=await fixture();const e=make();expect(e.snapshot().version).toBeNull();expect(await e.refreshInstalledState()).toMatchObject({version:'0.2.0',installedUpstream:'0.1.7',phase:'stopped'});expect(network).not.toHaveBeenCalled();});
it('a restarted engine reuses the same durable installation',async()=>{const {make,root}=await fixture();await make().refreshInstalledState();const before=await fs.readFile(path.join(root,'active.json'),'utf8');expect((await make().refreshInstalledState()).version).toBe('0.2.0');expect(await fs.readFile(path.join(root,'active.json'),'utf8')).toBe(before);expect(network).not.toHaveBeenCalled();});
it('an explicitly absent installation clears stale display state',async()=>{const {make,root}=await fixture();const e=make();await e.refreshInstalledState();await fs.unlink(path.join(root,'active.json'));expect(await e.refreshInstalledState()).toMatchObject({version:null,installedUpstream:null});});
it('a corrupt active record surfaces an error, not a request to silently download',async()=>{const {make,root}=await fixture();await fs.writeFile(path.join(root,'active.json'),'{broken');await expect(make().refreshInstalledState()).rejects.toThrow();expect(network).not.toHaveBeenCalled();});
it('same and older bundles are not normal upgrades; newer bundles are',()=>{expect(isNewerBundle('0.2.0','0.2.0')).toBe(false);expect(isNewerBundle('0.1.9','0.2.0')).toBe(false);expect(isNewerBundle('0.2.1','0.2.0')).toBe(true);});
