import {describe,it,expect,vi} from 'vitest';
import {runTemplateGeneration,templateGenerationArgs} from './harness-generation-workflow';
const req={tool:'langbai_generate_image',args:{count:1},sessionId:'session',callId:'root'};
describe('approved template image transaction',()=>{
 it('uses conversion output exactly once without recursively requesting approval',async()=>{const execute=vi.fn().mockResolvedValueOnce({ok:true,data:{result:'validated prompt',validation:{total:60}}}).mockResolvedValueOnce({ok:true,data:{count:1},generatedImages:[{id:'image'}]});const out=await runTemplateGeneration(req,{text:'白发'},execute,()=>true);expect(out.ok).toBe(true);expect(execute).toHaveBeenCalledTimes(2);expect(execute.mock.calls[1][0].args).toEqual({count:1,positivePrompt:'validated prompt'});});
 it('stops before generation after validation failure and marks no automatic retry',async()=>{const execute=vi.fn().mockResolvedValue({ok:false,output:'ratio invalid'});const result=await runTemplateGeneration(req,{text:'白发'},execute,()=>true);expect(result.ok).toBe(false);expect(result.output).toContain('不要自动');expect(execute).toHaveBeenCalledTimes(1);});
 it('does not generate when stopped or settings change during conversion',async()=>{const control=new AbortController();const execute=vi.fn(async()=>{control.abort();return {ok:true,title:'ok',output:'',data:{result:'prompt'}};});await expect(runTemplateGeneration({...req,signal:control.signal},{text:'scene'},execute,()=>true)).rejects.toThrow();expect(execute).toHaveBeenCalledTimes(1);execute.mockImplementation(async()=>({ok:true,title:'ok',output:'',data:{result:'prompt'}}));expect((await runTemplateGeneration(req,{text:'scene'},execute,()=>false)).ok).toBe(false);expect(execute).toHaveBeenCalledTimes(2);});
 it('does not accept model supplied authorization or arbitrary image arguments',()=>{expect(()=>templateGenerationArgs({text:'scene',approved:true})).toThrow();expect(()=>templateGenerationArgs({text:'scene',generate:{approved:true}})).toThrow();expect(templateGenerationArgs({text:'scene',generate:{count:1}})).toEqual({count:1});});
});
