import {it,expect,vi} from 'vitest';
const mock=vi.hoisted(()=>({popup:null as any}));
vi.mock('electron',async()=>{const {EventEmitter}=await import('node:events');return {BrowserWindow:class extends EventEmitter{options:any;webContents:any;destroyed=false;setBounds=vi.fn();show=vi.fn();focus=vi.fn();setMenu=vi.fn();constructor(options:any){super();this.options=options;this.webContents=Object.assign(new EventEmitter(),{setWindowOpenHandler:vi.fn()});mock.popup=this;}loadURL=vi.fn(async()=>{});isDestroyed=()=>this.destroyed;destroy(){this.destroyed=true;this.emit('closed');}},screen:{getCursorScreenPoint:()=>({x:500,y:400}),getDisplayMatching:()=>({workArea:{x:0,y:0,width:1920,height:1040}})}};});
import {exitDialogBounds,exitDialogHTML,showCenteredExitConfirmation} from './harness-exit-dialog';
it('centers on the software window in DIP rather than screen origin',()=>{expect(exitDialogBounds({x:200,y:160,width:1200,height:800},{x:0,y:0,width:1920,height:1040})).toEqual({x:590,y:450,width:420,height:220});});
it('handles negative-coordinate monitors, moved/offscreen windows and small work areas',()=>{for(const work of [{x:-1920,y:0,width:1920,height:1040},{x:1920,y:0,width:1536,height:824},{x:0,y:0,width:360,height:240}]){const r=exitDialogBounds({x:-9000,y:-5000,width:1200,height:800},work);expect(r.x).toBeGreaterThanOrEqual(work.x);expect(r.y).toBeGreaterThanOrEqual(work.y);expect(r.x+r.width).toBeLessThanOrEqual(work.x+work.width);expect(r.y+r.height).toBeLessThanOrEqual(work.y+work.height);}});
it('defaults keyboard focus to cancel and escapes translated content',()=>{const html=exitDialogHTML({title:'退出',message:'关闭 <Agent>',detail:'任务会中断',buttons:['取消退出','确认退出']});expect(html).toContain('&lt;Agent&gt;');expect(html).toContain('id="cancel" autofocus');expect(html).toContain("e.key==='Escape'");expect(html).not.toContain('require(');});
it('restores minimized owner, explicitly places popup and resolves confirm only once',async()=>{const owner={isDestroyed:()=>false,isMinimized:()=>true,isVisible:()=>false,getNormalBounds:()=>({x:200,y:160,width:1200,height:800}),restore:vi.fn(),show:vi.fn()};const p=showCenteredExitConfirmation(owner as any,{title:'退出',message:'退出？',detail:'中断任务',buttons:['取消','退出']});const win=mock.popup;win.emit('ready-to-show');expect(owner.restore).toHaveBeenCalledTimes(1);expect(win.setBounds).toHaveBeenCalledWith({x:590,y:450,width:420,height:220});expect(win.options.parent).toBe(owner);expect(win.options.modal).toBe(true);win.webContents.emit('will-navigate',{preventDefault:vi.fn()},'studio-exit://confirm');expect(await p).toEqual({response:1});expect(win.destroyed).toBe(true);});
it('closing the dialog or pressing escape cancels instead of stopping the Agent',async()=>{const p=showCenteredExitConfirmation(null,{title:'退出',message:'退出？',detail:'中断任务',buttons:['取消','退出']});mock.popup.emit('closed');expect(await p).toEqual({response:0});});

it('uses a frameless modal card without weakening renderer isolation',async()=>{const p=showCenteredExitConfirmation(null,{title:'Exit',message:'Exit Studio?',detail:'Agent tasks will stop.',buttons:['Cancel exit','Close Agent and exit']},true);const win=mock.popup;expect(win.options).toMatchObject({frame:false,transparent:true,hasShadow:true,backgroundColor:'#00000000',webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true}});win.emit('closed');expect(await p).toEqual({response:0});});
it('uses semantic light/dark styling, accessible labels and reduced motion',()=>{const opts={title:'<Exit>',message:'Exit Studio?',detail:'Agent tasks will stop.',buttons:['Cancel exit','Close Agent and exit']};for(const dark of [false,true]){const html=exitDialogHTML(opts,dark);expect(html).toContain('role="alertdialog"');expect(html).toContain('aria-describedby="detail"');expect(html).toContain('prefers-reduced-motion:reduce');expect(html).toContain('min-height:40px');expect(html).toContain('@media(pointer:coarse){button{min-height:44px}}');expect(html).toContain(dark?'--accent:#9d82f0':'--accent:#7047d8');expect(html).toContain('<title>&lt;Exit&gt;</title>');}});
