import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import sharp from 'sharp';
const f=vi.hoisted(()=>({root:'',handlers:new Map<string,Function>(),sender:{mainFrame:{},isDestroyed:()=>false,send:()=>{}}}));
vi.mock('electron',()=>({app:{isPackaged:false,getPath:(name:string)=>name==='exe'?path.join(f.root,'app/client.exe'):path.join(f.root,name),getAppPath:()=>path.join(f.root,'app')},ipcMain:{handle:(n:string,fn:Function)=>f.handlers.set(n,fn)},safeStorage:{isEncryptionAvailable:()=>true,encryptString:(s:string)=>Buffer.from(s).map(x=>x^73),decryptString:(b:Buffer)=>Buffer.from(b).map(x=>x^73).toString()}}));
vi.mock('./proxy',()=>({proxyConfigForUrl:async()=>({proxy:false})}));
const config={baseUrl:'https://owned-relay.invalid/custom/v1',model:'nai-diffusion-5-full',size:'1024x1024',responseFormat:'b64_json' as const};
const event=()=>({sender:f.sender,senderFrame:f.sender.mainFrame});
const call=(name:string,...args:unknown[])=>f.handlers.get(name)!(event(),...args);
beforeEach(()=>{f.root=fs.mkdtempSync(path.join(os.tmpdir(),'issue32-owned-'));f.handlers.clear();vi.resetModules();});
afterEach(()=>{vi.restoreAllMocks();if(path.dirname(f.root)!==path.resolve(os.tmpdir())||!path.basename(f.root).startsWith('issue32-owned-'))throw Error('Unsafe fixture');fs.rmSync(f.root,{force:true,recursive:true});});
async function setup(){const s=await import('./store');s.setToken('QA_OFFICIAL_NEVER_FORWARD');s.setSetting('outputDir',path.join(f.root,'output'));const ipc=await import('./compatible-settings-ipc');ipc.registerCompatibleImageIpc(()=>({isDestroyed:()=>false,webContents:f.sender}) as any);const axios=(await import('axios')).default;const get=vi.spyOn(axios,'get').mockResolvedValue({status:200,data:{data:[{id:config.model},{id:'gpt-image-1'}]}});const post=vi.fn();vi.spyOn(axios,'create').mockReturnValue({post,get} as any);return{s,axios,get,post};}
it('readonly validation then encrypted save activates independent NovelAI envelope, native token unchanged',async()=>{const {s,get,post}=await setup();const reply=await call('images:saveCompatibleSettings',config,'QA_RELAY_ONLY','openai-images',s.getSettings().imageServiceRevision);expect(reply.ok).toBe(true);expect(get).toHaveBeenCalledWith('https://owned-relay.invalid/custom/v1/models',expect.objectContaining({headers:{Authorization:'Bearer QA_RELAY_ONLY'},maxRedirects:0}));expect(post).not.toHaveBeenCalled();expect(s.getSettings().imageProvider).toBe('openai-images');expect(s.getToken()).toBe('QA_OFFICIAL_NEVER_FORWARD');expect(fs.readFileSync(path.join(f.root,'userData/novelai-image-desktop.json'),'utf8')).not.toContain('QA_RELAY_ONLY');});
for(const mode of ['401','404','html','non-novelai'] as const)it(`failed ${mode} validation never saves`,async()=>{const {s,get,post}=await setup();const before=fs.readFileSync(path.join(f.root,'userData/novelai-image-desktop.json'));get.mockResolvedValue({status:mode==='401'?401:mode==='404'?404:200,data:mode==='html'?'<html>SPA</html>':{data:[{id:'gpt-image-1'}]}});const result=await call('images:saveCompatibleSettings',config,'QA_RELAY_ONLY','openai-images',s.getSettings().imageServiceRevision);expect(result.ok).toBe(false);expect(fs.readFileSync(path.join(f.root,'userData/novelai-image-desktop.json'))).toEqual(before);expect(post).not.toHaveBeenCalled();});
it('explicitly rejects unrelated models before networking or persistence',async()=>{const {s,get,post}=await setup();const result=await call('images:saveCompatibleSettings',{...config,model:'gpt-image-1'},'QA_RELAY_ONLY','openai-images',s.getSettings().imageServiceRevision);expect(result.ok).toBe(false);expect(get).not.toHaveBeenCalled();expect(post).not.toHaveBeenCalled();});
it('reachable generation performs one POST, decodes PNG, writes real history, and switching native retains independent config',async()=>{const {s,post}=await setup();expect((await call('images:saveCompatibleSettings',config,'QA_RELAY_ONLY','openai-images',s.getSettings().imageServiceRevision)).ok).toBe(true);const bytes=await sharp({create:{width:2,height:2,channels:3,background:'white'}}).png().toBuffer();post.mockResolvedValue({status:200,data:Buffer.from(JSON.stringify({data:[{b64_json:bytes.toString('base64')}]}))});const result=await call('images:generateCompatible',{prompt:'owned fixture',n:1,expectedImageServiceRevision:s.getSettings().imageServiceRevision});expect(result.ok).toBe(true);expect(result.items).toHaveLength(1);expect(fs.existsSync(result.items[0].filePath)).toBe(true);expect(post).toHaveBeenCalledTimes(1);expect(post.mock.calls[0][0]).toBe('https://owned-relay.invalid/custom/v1/images/generations');expect(post.mock.calls[0][2]?.headers?.Authorization).toBe('Bearer QA_RELAY_ONLY');expect(JSON.stringify(post.mock.calls)).not.toContain('QA_OFFICIAL_NEVER_FORWARD');expect((await call('images:setCompatibleProvider','novelai',s.getSettings().imageServiceRevision)).ok).toBe(true);expect(s.getSettings()).toMatchObject({imageProvider:'novelai',imageApiKey:'QA_RELAY_ONLY',compatibleImage:config});});
it('stale or remote renderer cannot save or submit',async()=>{const {s,get,post}=await setup();expect((await call('images:saveCompatibleSettings',config,'QA_RELAY_ONLY','openai-images','stale')).ok).toBe(false);expect((await f.handlers.get('images:saveCompatibleSettings')!({sender:{},senderFrame:{}},config,'QA_RELAY_ONLY','openai-images',s.getSettings().imageServiceRevision)).ok).toBe(false);expect((await call('images:generateCompatible',{prompt:'fixture',n:1,expectedImageServiceRevision:'stale'})).ok).toBe(false);expect(get).not.toHaveBeenCalled();expect(post).not.toHaveBeenCalled();});
