import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {NAI_RELAY_MODEL_IDS} from '../../src/nai-accounts';
const fixture=vi.hoisted(()=>({root:'',handlers:new Map<string,Function>()}));
vi.mock('electron',()=>({ipcMain:{handle:(n:string,f:Function)=>fixture.handlers.set(n,f)},app:{isPackaged:false,getPath:()=>fixture.root,getAppPath:()=>fixture.root},safeStorage:{isEncryptionAvailable:()=>true,encryptString:(s:string)=>Buffer.from(s).map(x=>x^73),decryptString:(b:Buffer)=>Buffer.from(b).map(x=>x^73).toString()}}));
beforeEach(()=>{fixture.root=fs.mkdtempSync(path.join(os.tmpdir(),'novelai-only-'));fixture.handlers.clear();vi.resetModules();});
afterEach(()=>{vi.restoreAllMocks();if(path.dirname(fixture.root)!==path.resolve(os.tmpdir())||!path.basename(fixture.root).startsWith('novelai-only-'))throw Error('Invalid fixture');fs.rmSync(fixture.root,{recursive:true,force:true});});
it('migrates a retired provider without copying credentials or changing NovelAI endpoints and retry consent',async()=>{
 fs.writeFileSync(path.join(fixture.root,'novelai-image-desktop.json'),JSON.stringify({token:'fixture-native-token',settings:{imageProvider:'openai-images',imageApiKey:'fixture-old-key',compatibleImage:{baseUrl:'https://old.example/v1',model:'old'},apiBaseUrl:'https://api.novelai.net',imageBaseUrl:'https://relay.example',allowCustomEndpoint:true,allowCustomEndpointFallback:false}}));
 const {getSettings,getToken}=await import('./store');const s=getSettings();expect(s).toMatchObject({imageProvider:'novelai',imageApiKey:'fixture-old-key',imageBaseUrl:'https://relay.example',allowCustomEndpoint:true,allowCustomEndpointFallback:false});expect(s.compatibleImage?.baseUrl).toBe('https://old.example/v1');expect(getToken()).toBe('fixture-native-token');
});
it('keeps unsupported models inactive through low-level setters and imported provider flags',async()=>{
 const store=await import('./store');store.setToken('fixture-native-token');const before=store.getSettings();
 expect(()=>store.setSetting('imageProvider','unrelated-provider' as any)).toThrow('NovelAI');
 store.setSetting('imageProvider','openai-images');expect(store.getSettings().imageProvider).toBe('novelai');
 store.setCompatibleImageSettings({baseUrl:'https://old.example',model:'old'},'fixture-key','openai-images');expect(store.getSettings().imageProvider).toBe('novelai');expect(store.getToken()).toBe('fixture-native-token');expect(store.getSettings().imageApiKey).toBe('fixture-key');
 store.writeStore({...store.readStore(),settings:{...before,imageProvider:'openai-images'}});expect(store.getSettings().imageProvider).toBe('novelai');
});
it.each(['images:saveCompatibleSettings','images:setCompatibleProvider','images:generateCompatible'])('malformed legacy call to %s is rejected without a request or settings change',async channel=>{
 const send=vi.fn(),frame={},webContents={mainFrame:frame,isDestroyed:()=>false,send};const {registerCompatibleImageIpc}=await import('./compatible-settings-ipc');registerCompatibleImageIpc(()=>({isDestroyed:()=>false,webContents}) as any);
 const {getSettings}=await import('./store');const before=getSettings(),axios=(await import('axios')).default,get=vi.spyOn(axios,'get'),post=vi.spyOn(axios,'post'),fetcher=vi.spyOn(globalThis,'fetch');const r=await fixture.handlers.get(channel)!({sender:webContents,senderFrame:frame},'openai-images',before.imageServiceRevision);expect(r.ok).toBe(false);if(channel!=='images:setCompatibleProvider')expect(r.code).toBe('stale');else expect(r.message).toContain('保存配置');expect(getSettings()).toEqual(before);expect(fetcher).not.toHaveBeenCalled();expect(get).not.toHaveBeenCalled();expect(post).not.toHaveBeenCalled();expect(JSON.stringify(r)).not.toContain('fixture-key');
});
it('only the owned renderer can access independent NovelAI envelope channels and settings notifications',async()=>{
 const mainFrame={},webContents={mainFrame,isDestroyed:()=>false,send:vi.fn()};const {registerCompatibleImageIpc}=await import('./compatible-settings-ipc');registerCompatibleImageIpc(()=>({isDestroyed:()=>false,webContents}) as any);
 expect(await fixture.handlers.get('images:generateCompatible')!({sender:{},senderFrame:mainFrame})).toMatchObject({ok:false,code:'stale'});
});
it.each(NAI_RELAY_MODEL_IDS)('preserves explicit independent envelope opt-in for supported NovelAI identity %s',async model=>{
 const store=await import('./store');store.setToken('fixture-native-token');const before=store.getSettings();store.setCompatibleImageSettings({baseUrl:'https://images.example.invalid/v1',model,size:'auto',responseFormat:'auto'},'fixture-independent-key','openai-images');expect(store.getSettings()).toMatchObject({imageProvider:'openai-images',imageApiKey:'fixture-independent-key',compatibleImage:{model}});expect(store.getSettings().apiBaseUrl).toBe(before.apiBaseUrl);expect(store.getSettings().imageBaseUrl).toBe(before.imageBaseUrl);expect(store.getToken()).toBe('fixture-native-token');
});
it('valid IPC save verifies the selected NovelAI identity with only its independent key and a read-only GET',async()=>{
 const frame={},webContents={mainFrame:frame,isDestroyed:()=>false,send:vi.fn()};const {registerCompatibleImageIpc}=await import('./compatible-settings-ipc');registerCompatibleImageIpc(()=>({isDestroyed:()=>false,webContents}) as any);const store=await import('./store');store.setToken('fixture-native-token');vi.spyOn((await import('./proxy')),'proxyConfigForUrl').mockResolvedValue({proxy:false});const axios=(await import('axios')).default,get=vi.spyOn(axios,'get').mockResolvedValue({status:200,data:{data:[{id:'nai-diffusion-5-full'}]}}),post=vi.spyOn(axios,'post'),fetcher=vi.spyOn(globalThis,'fetch');const config={baseUrl:'https://images.example.invalid/v1',model:'nai-diffusion-5-full',size:'auto',responseFormat:'auto',extensions:{}};
 const result=await fixture.handlers.get('images:saveCompatibleSettings')!({sender:webContents,senderFrame:frame},config,'fixture-independent-key','openai-images',store.getSettings().imageServiceRevision);expect(result.ok).toBe(true);expect(get).toHaveBeenCalledTimes(1);expect(get).toHaveBeenCalledWith('https://images.example.invalid/v1/models',expect.objectContaining({maxRedirects:0,headers:{Authorization:'Bearer fixture-independent-key'}}));expect(post).not.toHaveBeenCalled();expect(fetcher).not.toHaveBeenCalled();expect(store.getSettings()).toMatchObject({imageProvider:'openai-images',imageApiKey:'fixture-independent-key',compatibleImage:{model:'nai-diffusion-5-full'}});expect(store.getToken()).toBe('fixture-native-token');
});
it.each(['auth','missing-model'])('failed read-only IPC verification %s leaves settings and encrypted store unchanged',async mode=>{
 const frame={},webContents={mainFrame:frame,isDestroyed:()=>false,send:vi.fn()};const {registerCompatibleImageIpc}=await import('./compatible-settings-ipc');registerCompatibleImageIpc(()=>({isDestroyed:()=>false,webContents}) as any);const store=await import('./store');const before=store.getSettings(),file=path.join(fixture.root,'novelai-image-desktop.json'),bytes=fs.readFileSync(file);vi.spyOn((await import('./proxy')),'proxyConfigForUrl').mockResolvedValue({proxy:false});const axios=(await import('axios')).default,get=vi.spyOn(axios,'get').mockResolvedValue(mode==='auth'?{status:401,data:{}}:{status:200,data:{data:[{id:'unrelated-image-model'}]}}),post=vi.spyOn(axios,'post'),fetcher=vi.spyOn(globalThis,'fetch');
 const result=await fixture.handlers.get('images:saveCompatibleSettings')!({sender:webContents,senderFrame:frame},{baseUrl:'https://images.example.invalid/v1',model:'nai-diffusion-5-full',size:'auto',responseFormat:'auto',extensions:{}},'fixture-independent-key','openai-images',before.imageServiceRevision);expect(result.ok).toBe(false);expect(result.message).toContain('未保存');expect(get).toHaveBeenCalledTimes(1);expect(post).not.toHaveBeenCalled();expect(fetcher).not.toHaveBeenCalled();expect(store.getSettings()).toEqual(before);expect(fs.readFileSync(file)).toEqual(bytes);
});
it('unsupported model IPC save rejects before any request and preserves the encrypted store',async()=>{
 const frame={},webContents={mainFrame:frame,isDestroyed:()=>false,send:vi.fn()};const {registerCompatibleImageIpc}=await import('./compatible-settings-ipc');registerCompatibleImageIpc(()=>({isDestroyed:()=>false,webContents}) as any);const store=await import('./store');const before=store.getSettings(),file=path.join(fixture.root,'novelai-image-desktop.json'),bytes=fs.readFileSync(file);const axios=(await import('axios')).default,get=vi.spyOn(axios,'get'),post=vi.spyOn(axios,'post'),fetcher=vi.spyOn(globalThis,'fetch');
 const result=await fixture.handlers.get('images:saveCompatibleSettings')!({sender:webContents,senderFrame:frame},{baseUrl:'https://images.example.invalid/v1',model:'unrelated-image-model',size:'auto',responseFormat:'auto',extensions:{}},'fixture-independent-key','openai-images',before.imageServiceRevision);expect(result.ok).toBe(false);expect(get).not.toHaveBeenCalled();expect(post).not.toHaveBeenCalled();expect(fetcher).not.toHaveBeenCalled();expect(store.getSettings()).toEqual(before);expect(fs.readFileSync(file)).toEqual(bytes);
});
it.each(['read','configure','credential','clearCredential','test'])('Agent rejects retired image profile action %s before approval or networking',async action=>{
 const {createApiTools,desktopApiAdapter}=await import('./agent-api-tools');const approve=vi.fn(async()=>true),fetcher=vi.spyOn(globalThis,'fetch'),api=createApiTools(desktopApiAdapter(),approve);
 const r=await api.execute({tool:'langbai_api',sessionId:'fixture',args:{action,profile:'compatible-image',patch:{enabled:true},expectedRevision:'old'}});expect(r.ok).toBe(false);expect(approve).not.toHaveBeenCalled();expect(fetcher).not.toHaveBeenCalled();
});
