import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import sharp from "sharp";
import { afterEach, expect, it } from "vitest";
import { scanOutputImages } from "./output-images";
import { localMediaUrlToPath } from "./local-media-protocol";
const roots: string[] = [];
afterEach(async () => { for (const root of roots.splice(0)) await fs.rm(root, { recursive: true, force: true }); });
it("loads existing root and legacy folder images, excludes invalid files, and preserves known metadata", async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "nai-output-")); roots.push(root);
  await fs.mkdir(path.join(root, "2026-01-01"));
  const bytes = await sharp({ create: { width: 12, height: 8, channels: 3, background: "red" } }).png().toBuffer();
  await fs.writeFile(path.join(root, "作品.png"), bytes);
  await fs.writeFile(path.join(root, "2026-01-01", "old.png"), bytes);
  await fs.writeFile(path.join(root, "broken.png"), "invalid");
  await fs.writeFile(path.join(root, "notes.txt"), "text");
  const first = await scanOutputImages(root, []);
  expect(first).toHaveLength(2);
  expect(first.every(item => item.width === 12 && item.height === 8)).toBe(true);
  expect(first.every(item => localMediaUrlToPath(item.fileUrl) === item.filePath)).toBe(true);
  const known = { ...first[0], model: "saved-model", actualSeed: 42, groupId: "old-group" };
  const next = await scanOutputImages(root, [known]);
  expect(next.find(item => item.id === known.id)).toMatchObject({ model: "saved-model", actualSeed: 42, groupId: "old-group" });
  const other = await fs.mkdtemp(path.join(os.tmpdir(), "nai-output-other-")); roots.push(other);
  expect(await scanOutputImages(other, first)).toEqual([]);
  await fs.unlink(first[0].filePath);
  expect(await scanOutputImages(root, first)).toHaveLength(1);
});
