import {describe,it,expect} from 'vitest';
import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import crypto from 'node:crypto';
import * as helpers from '../../src/translation';
import * as promptHelpers from '../../src/google-prompt-translation';
function production(){const ast=ts.createSourceFile('nai.ts',fs.readFileSync('electron/ipc/nai.ts','utf8'),ts.ScriptTarget.Latest,true);const names=['translateText','aiTranslate','baiduTranslate','googleTranslate'];const code=ts.transpileModule(names.map(name=>ast.statements.find((n):n is ts.FunctionDeclaration=>ts.isFunctionDeclaration(n)&&n.name?.text===name)!.getText(ast)).join('\n'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 const settings:any={language:'ja-JP',translateTargetLanguage:'system',translateProvider:'google',baiduAppId:'fixture',baiduSecret:'fixture',translateAiApiUrl:'https://fixture.invalid',translateAiApiKey:'fixture',translateAiModel:'fixture'};const calls:any[]=[];let aiOutput="translated";
 const axios={get:async(url:string,options:any)=>{calls.push({url,options});return {data:url.includes('baidu')?{from:'en',trans_result:[{dst:'translated'}]}:[[[options.params.q.split('\n').map(()=> 'translated').join('\n')]],null,'en']};},post:async(url:string,payload:any)=>{calls.push({url,payload});return {data:{choices:[{message:{content:aiOutput}}]}};}};
 const api=vm.runInNewContext(code+'\n({'+names.join(',')+'})',{...helpers,...promptHelpers,searchDanbooru:async()=>[],exports:{},axios,crypto,getSettings:()=>settings,proxyConfig:()=>({}),cleanPromptOutput:(s:string)=>s,recordAiCall:()=>{},Date});return{api,settings,calls,setAiOutput:(text:string)=>aiOutput=text};}
describe('production translation dispatch',()=>{
 for(const provider of ['google','baidu','ai'])for(const language of helpers.TRANSLATION_LANGUAGES)it(`${provider}: explicit ${language.value}`,async()=>{const {api,settings,calls}=production();settings.translateProvider=provider;const result=await api.translateText('red coat, 1.2::blue hair::',language.value);expect(result.ok).toBe(true);if(provider==='ai'){expect(calls[0].payload.messages[0].content).toContain(language.name);if(language.value!=='en')expect(calls[0].payload.messages[0].content).toContain('Translate the words, including English tags');}else expect(calls[0].options.params[provider==='google'?'tl':'to']).toBe(provider==='google'?language.value:language.baidu);});
 it('omitted target follows saved selection or software language; conversion can explicitly request English',async()=>{const {api,settings,calls}=production();await api.translateText('word');expect(calls.at(-1).options.params.tl).toBe('ja');settings.translateTargetLanguage='zh-TW';await api.translateText('word');expect(calls.at(-1).options.params.tl).toBe('zh-TW');await api.translateText('word','en');expect(calls.at(-1).options.params.tl).toBe('en');});
 it('empty source never sends a request',async()=>{const {api,calls}=production();expect((await api.translateText('  ')).ok).toBe(false);expect(calls).toHaveLength(0);});
 for(const provider of ['google','baidu','ai'])it(`${provider}: explicit source survives dispatch; older callers still auto`,async()=>{const {api,settings,calls}=production();settings.translateProvider=provider;const r=await api.translateText('words','ja','zh-TW');expect(r.sourceLanguage).toBe('zh-TW');if(provider==='ai')expect(calls[0].payload.messages[0].content).toContain('Traditional Chinese');else expect(calls[0].options.params[provider==='google'?'sl':'from']).toBe(provider==='google'?'zh-TW':'cht');await api.translateText('words','en');if(provider!=='ai')expect(calls[1].options.params[provider==='google'?'sl':'from']).toBe('auto');});
 for(const provider of ['google','baidu'])it(`${provider}: detected language returned for swap`,async()=>{const {api,settings}=production();settings.translateProvider=provider;expect((await api.translateText('words','zh-CN')).sourceLanguage).toBe('en');});

 it('AI JSON carries real detected source; empty text is not a success',async()=>{const {api,settings,setAiOutput}=production();settings.translateProvider='ai';setAiOutput('```json\n{"text":"你好","sourceLanguage":"en-US"}\n```');expect(await api.translateText('hello','zh-CN')).toMatchObject({ok:true,text:'你好',sourceLanguage:'en'});setAiOutput('{"text":" ","sourceLanguage":"en"}');expect((await api.translateText('hello','zh-CN')).ok).toBe(false);});

});
