import {it,expect} from 'vitest';
import {combinedUpdateKind} from './harness-update-status';
import type {HarnessSnapshot} from './harness-types';
const snapshot=():HarnessSnapshot=>({phase:'stopped',version:'0.1.7',installedUpstream:'0.1.7-rc.2',logs:[],dataDirectory:'',updateInfo:{checkedAt:'',component:'0.1.8',official:'0.2.0-rc.2',plugins:{},errors:[]}});
it('uses one component update when both versions are newer',()=>expect(combinedUpdateKind(snapshot())).toBe('component'));
it('checks official compatibility even when component is current',()=>{const s=snapshot();s.updateInfo!.component='0.1.7';expect(combinedUpdateKind(s)).toBe('official');});
it('does not offer while checks are incomplete',()=>{const s=snapshot();s.checkingUpdates=true;expect(combinedUpdateKind(s)).toBeNull();s.checkingUpdates=false;s.updateInfo=null;expect(combinedUpdateKind(s)).toBeNull();});
it('does not offer current or older versions',()=>{const s=snapshot();s.updateInfo!.component='0.1.6';s.updateInfo!.official='0.1.7-rc.2';expect(combinedUpdateKind(s)).toBeNull();});
it('does not trust failed-source versions',()=>{const s=snapshot();s.updateInfo!.componentFailed=true;expect(combinedUpdateKind(s)).toBe('official');s.updateInfo!.officialFailed=true;expect(combinedUpdateKind(s)).toBeNull();});
it('can offer an initial component install without claiming an official update',()=>{const s=snapshot();s.version=null;s.installedUpstream=null;expect(combinedUpdateKind(s)).toBe('component');s.updateInfo!.component=null;expect(combinedUpdateKind(s)).toBeNull();});
