import {describe,it,expect,vi} from 'vitest';
import {createElement,createRef} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {readFileSync} from 'node:fs';
import {naiAccountTabKey,NAI_ACCOUNT_METHODS} from './nai-accounts';
vi.mock('./store',()=>({useAppStore:()=>undefined}));
import {NaiAccountDialogFrame} from './components/NaiAccountManager';
describe('accessible account dialog',()=>{
 it('has no editable OTP and inherits theme surfaces instead of forcing dark colors',()=>{const source=readFileSync('src/components/NaiAccountManager.tsx','utf8');const css=readFileSync('src/components/NaiAccountManager.css','utf8');expect(source).not.toContain('value={otp}');expect(source).not.toContain('setOtp');expect(source).toContain("nt('loginSafety')");for(const name of ['text','muted','border','accent'])expect(css).toContain(`var(--${name})`);expect(css).toContain('var(--panel,var(--bg-dialog))');expect(css).toContain('var(--panel-2,var(--bg-input))');expect(css).not.toMatch(/#[0-9a-f]{3,8}\b/i);});
 it('renders named modal dialog and explicit close button',()=>{const html=renderToStaticMarkup(createElement(NaiAccountDialogFrame,{title:'NovelAI accounts',closeLabel:'Close',titleId:'accounts-title',panelRef:createRef<HTMLDivElement>(),onClose:()=>{},children:'fixture'}));expect(html).toContain('role="dialog"');expect(html).toContain('aria-modal="true"');expect(html).toContain('aria-labelledby="accounts-title"');expect(html).toContain('aria-label="Close"');expect(html).toContain('id="accounts-title"');});
 it('implements three roving tabs and keyboard wrap/home/end',()=>{expect(NAI_ACCOUNT_METHODS).toHaveLength(3);expect(naiAccountTabKey('relay','ArrowRight')).toBe('token');expect(naiAccountTabKey('token','ArrowLeft')).toBe('relay');expect(naiAccountTabKey('official-login','Home')).toBe('token');expect(naiAccountTabKey('official-login','End')).toBe('relay');});
 it('keeps Escape, backdrop/close cleanup, focus trapping and confirmation guards in the live component',()=>{const source=readFileSync('src/components/NaiAccountManager.tsx','utf8');expect(source).toContain("event.key==='Escape'");expect(source).toContain("event.key!=='Tab'");expect(source).toContain("setToken('');setPassword('')");expect(source).toContain('clearSecrets();setOpen(false);trigger.current?.focus()');expect(source).toContain('window.confirm');expect(source).toContain('role="tablist"');expect(source).toContain('role="tab"');expect(source).toContain('role="tabpanel"');expect(source).toContain('createPortal');expect(source).not.toMatch(/console\.|localStorage|sessionStorage/);expect(source).toContain('autoComplete="off"');});
});
